/**
 * Generated FORGE API bindings for Task Manager.
 *
 * This file would normally be auto-generated by `forge generate`.
 */

import { createQuery, createMutation, createAction } from '@forge/svelte';

// Types
export interface Team {
	id: string;
	name: string;
	slug: string;
	description: string | null;
	createdAt: string;
	updatedAt: string;
}

export interface Project {
	id: string;
	teamId: string;
	name: string;
	description: string | null;
	status: ProjectStatus;
	color: string | null;
	createdAt: string;
	updatedAt: string;
}

export interface Task {
	id: string;
	projectId: string;
	title: string;
	description: string | null;
	status: TaskStatus;
	priority: TaskPriority;
	assigneeId: string | null;
	dueDate: string | null;
	position: number;
	createdBy: string;
	createdAt: string;
	updatedAt: string;
}

export interface Comment {
	id: string;
	taskId: string;
	authorId: string;
	content: string;
	createdAt: string;
	updatedAt: string;
}

export interface User {
	id: string;
	email: string;
	name: string;
	avatarUrl: string | null;
}

// Enums
export type TaskStatus = 'backlog' | 'todo' | 'in_progress' | 'in_review' | 'done' | 'cancelled';
export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent';
export type ProjectStatus = 'active' | 'on_hold' | 'completed' | 'archived';
export type TeamRole = 'owner' | 'admin' | 'member' | 'guest';

// Query args types
export interface GetTeamArgs {
	teamId: string;
}

export interface GetTeamProjectsArgs {
	teamId: string;
}

export interface GetProjectTasksArgs {
	projectId: string;
	status?: TaskStatus;
	limit?: number;
	offset?: number;
}

export interface GetTaskDetailsArgs {
	taskId: string;
}

export interface GetTaskCommentsArgs {
	taskId: string;
}

export interface SearchTasksArgs {
	projectId: string;
	query: string;
	limit?: number;
}

// Mutation input types
export interface CreateTeamInput {
	name: string;
	description?: string;
}

export interface CreateProjectInput {
	teamId: string;
	name: string;
	description?: string;
	color?: string;
}

export interface CreateTaskInput {
	projectId: string;
	title: string;
	description?: string;
	priority?: TaskPriority;
	assigneeId?: string;
	dueDate?: string;
}

export interface UpdateTaskInput {
	title?: string;
	description?: string;
	status?: TaskStatus;
	priority?: TaskPriority;
	assigneeId?: string;
	dueDate?: string;
	position?: number;
}

export interface CreateCommentInput {
	taskId: string;
	content: string;
}

// Queries
export const getTeam = createQuery<GetTeamArgs, Team | null>('get_team');
export const getTeamProjects = createQuery<GetTeamProjectsArgs, Project[]>('get_team_projects');
export const getProjectTasks = createQuery<GetProjectTasksArgs, Task[]>('get_project_tasks');
export const getTaskDetails = createQuery<GetTaskDetailsArgs, Task | null>('get_task_details');
export const getTaskComments = createQuery<GetTaskCommentsArgs, Comment[]>('get_task_comments');
export const searchTasks = createQuery<SearchTasksArgs, Task[]>('search_tasks');

// Mutations
export const createTeam = createMutation<CreateTeamInput, Team>('create_team');
export const createProject = createMutation<CreateProjectInput, Project>('create_project');
export const createTask = createMutation<CreateTaskInput, Task>('create_task');
export const updateTask = createMutation<{ taskId: string } & UpdateTaskInput, Task>('update_task');
export const deleteTask = createMutation<{ taskId: string }, void>('delete_task');
export const addComment = createMutation<CreateCommentInput, Comment>('add_comment');
export const archiveProject = createMutation<{ projectId: string }, Project>('archive_project');

// Actions
export const sendNotification = createAction<{ userId: string; title: string; message: string }, { notificationId: string; sent: boolean }>('send_notification');
export const exportProjectCsv = createAction<{ projectId: string }, { exportId: string; downloadUrl: string; expiresAt: string }>('export_project_csv');
