//! Dioxus (Rust frontend) code generation.

mod api;
pub(crate) mod builder;
mod types;

use std::path::PathBuf;

use forge_core::schema::SchemaRegistry;

use crate::Error;
use crate::binding::BindingSet;

pub struct DioxusGenerator {
    output_dir: PathBuf,
}

impl DioxusGenerator {
    pub fn new(output_dir: impl Into<PathBuf>) -> Self {
        Self {
            output_dir: output_dir.into(),
        }
    }

    pub fn generate(&self, registry: &SchemaRegistry) -> Result<(), Error> {
        std::fs::create_dir_all(&self.output_dir)?;

        let bindings = BindingSet::from_registry(registry);

        std::fs::write(self.output_dir.join("types.rs"), types::generate(registry)?)?;
        std::fs::write(self.output_dir.join("api.rs"), api::generate(&bindings)?)?;
        std::fs::write(self.output_dir.join("mod.rs"), Self::mod_content())?;

        Ok(())
    }

    fn mod_content() -> &'static str {
        // Framework re-exports are explicit. The api/types globs are kept for
        // downstream ergonomics (users reach `get_user(…)` directly), but if a
        // user names a type collision-prone (`Mutation`, `QueryState`, …) the
        // resolution between `forge_dioxus::Mutation` and the user `Mutation`
        // becomes ambiguous. The framework imports are listed explicitly so
        // the conflict is at least visible in this file.
        r#"// @generated by FORGE - DO NOT EDIT

#![allow(dead_code, unused_imports)]

pub mod api;
pub mod types;

pub use api::*;
pub use forge_dioxus::{
    ConnectionState, ForgeAuth, ForgeAuthProvider, ForgeClient, ForgeClientConfig,
    ForgeClientError, ForgeError, ForgeProvider, ForgeUpload, JobExecutionState, Mutation,
    QueryState, SignalError, SubscriptionHandle, SubscriptionState, TokenPair, WorkflowExecutionState,
    use_auth_key, use_connection_state, use_forge_auth, use_forge_client, use_forge_job,
    use_forge_mutation, use_forge_query, use_forge_subscription, use_forge_workflow,
    use_viewer,
};
pub use types::*;
"#
    }
}
