//! Test context builders for all Forge function types.
//!
//! Every builder shares the same auth/env/pool fields and setter methods. Rather
//! than copy those byte-for-byte into eight files, the setters are generated by
//! the macros below — each builder opts into the clusters it supports
//! (`impl_test_auth_builder!`, `impl_test_env_builder!`, `impl_test_tenant_builder!`).

use crate::function::AuthContext;
use std::collections::HashMap;
use uuid::Uuid;

/// Generate the auth setter methods (`as_user`, `as_subject`, `with_role`,
/// `with_roles`, `with_claim`) for a test-context builder that carries
/// `user_id`, `roles`, and `claims` fields.
macro_rules! impl_test_auth_builder {
    ($builder:ty) => {
        impl $builder {
            /// Set the authenticated user with a UUID.
            pub fn as_user(mut self, id: uuid::Uuid) -> Self {
                self.user_id = Some(id);
                self
            }

            /// For non-UUID auth providers (Firebase, Clerk, etc.).
            pub fn as_subject(mut self, subject: impl Into<String>) -> Self {
                self.claims
                    .insert("sub".to_string(), serde_json::json!(subject.into()));
                self
            }

            /// Add a role.
            pub fn with_role(mut self, role: impl Into<String>) -> Self {
                self.roles.push(role.into());
                self
            }

            /// Add multiple roles.
            pub fn with_roles(mut self, roles: Vec<String>) -> Self {
                self.roles.extend(roles);
                self
            }

            /// Add a custom claim.
            pub fn with_claim(mut self, key: impl Into<String>, value: serde_json::Value) -> Self {
                self.claims.insert(key.into(), value);
                self
            }
        }
    };
}

/// Generate the env/pool setter methods (`with_env`, `with_envs`, `with_pool`)
/// for a test-context builder that carries `env_vars` and `pool` fields.
macro_rules! impl_test_env_builder {
    ($builder:ty) => {
        impl $builder {
            /// Set a single environment variable.
            pub fn with_env(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
                self.env_vars.insert(key.into(), value.into());
                self
            }

            /// Set multiple environment variables.
            pub fn with_envs(mut self, vars: std::collections::HashMap<String, String>) -> Self {
                self.env_vars.extend(vars);
                self
            }

            /// Set the database pool.
            pub fn with_pool(mut self, pool: sqlx::PgPool) -> Self {
                self.pool = Some(pool);
                self
            }
        }
    };
}

/// Generate the `with_tenant` setter for a builder that carries a `tenant_id`
/// field. Mirrors production: the value is also written into `claims` so
/// `auth.tenant_id()` reads identically to a real request.
macro_rules! impl_test_tenant_builder {
    ($builder:ty) => {
        impl $builder {
            /// Set the tenant ID for multi-tenant testing.
            pub fn with_tenant(mut self, tenant_id: uuid::Uuid) -> Self {
                self.tenant_id = Some(tenant_id);
                self.claims.insert(
                    "tenant_id".to_string(),
                    serde_json::Value::String(tenant_id.to_string()),
                );
                self
            }
        }
    };
}

mod cron;
mod daemon;
mod job;
mod mcp_tool;
mod mutation;
mod query;
mod webhook;
mod workflow;

pub use cron::{TestCronContext, TestCronContextBuilder};
pub use daemon::{TestDaemonContext, TestDaemonContextBuilder};
pub use job::{TestJobContext, TestJobContextBuilder, TestProgressUpdate};
pub use mcp_tool::{TestMcpToolContext, TestMcpToolContextBuilder};
pub use mutation::{TestMutationContext, TestMutationContextBuilder};
pub use query::{TestQueryContext, TestQueryContextBuilder};
pub use webhook::{TestWebhookContext, TestWebhookContextBuilder};
pub use workflow::{TestWorkflowContext, TestWorkflowContextBuilder};

/// Build an `AuthContext` from test builder fields.
pub(crate) fn build_test_auth(
    user_id: Option<Uuid>,
    roles: Vec<String>,
    claims: HashMap<String, serde_json::Value>,
) -> AuthContext {
    if let Some(user_id) = user_id {
        AuthContext::authenticated(user_id, roles, claims)
    } else if claims.contains_key("sub") {
        AuthContext::authenticated_without_uuid(roles, claims)
    } else {
        AuthContext::unauthenticated()
    }
}
