#!/usr/bin/env python3
"""Generate the Go outbox SQL constant from the canonical application migration."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "sql" / "forge_outbox_v1.sql"
OUTPUT = ROOT / "bindings" / "go" / "outbox_schema_gen.go"


def render() -> str:
    return (
        "// Code generated by tools/go-outbox-schema/generate.py. DO NOT EDIT.\n\n"
        "package forge\n\n"
        f"const OutboxSchemaSQL = {json.dumps(SOURCE.read_text(encoding='utf-8'))}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"stale generated file: {OUTPUT.relative_to(ROOT)}")
            return 1
        print("Go outbox schema matches canonical SQL")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
