// Code generated by tools/contract/generate.py. DO NOT EDIT.

package forge

// Job A leased queue job.
type Job struct {
	ID            string  `json:"id"`
	Receipt       string  `json:"receipt"`
	Payload       []byte  `json:"payload"`
	Attempt       uint32  `json:"attempt"`
	MaxAttempts   uint32  `json:"max_attempts"`
	LeasedUntilMs float64 `json:"leased_until_ms"`
	Queue         string  `json:"queue"`
	Traceparent   *string `json:"traceparent"`
	Tracestate    *string `json:"tracestate"`
	Baggage       *string `json:"baggage"`
}

// Decision A rate-limit decision.
type Decision struct {
	Allowed           bool     `json:"allowed"`
	Limit             uint32   `json:"limit"`
	Remaining         uint32   `json:"remaining"`
	ResetAfterSeconds float64  `json:"reset_after_seconds"`
	RetryAfterSeconds *float64 `json:"retry_after_seconds"`
}

// ApiKey A freshly minted API key whose secret is shown once.
type ApiKey struct {
	ID          string            `json:"id"`
	Secret      string            `json:"secret"`
	Label       string            `json:"label"`
	CreatedAtMs float64           `json:"created_at_ms"`
	ExpiresAtMs *float64          `json:"expires_at_ms"`
	Scopes      []string          `json:"scopes"`
	Metadata    map[string]string `json:"metadata"`
}

// QueueDepth Approximate queue depth.
type QueueDepth struct {
	Visible            uint64   `json:"visible"`
	InFlight           uint64   `json:"in_flight"`
	Delayed            uint64   `json:"delayed"`
	OldestVisibleAgeMs *float64 `json:"oldest_visible_age_ms"`
}

// DeadLetterInfo Payload-free operator metadata for one dead letter.
type DeadLetterInfo struct {
	JobID            string  `json:"job_id"`
	Queue            string  `json:"queue"`
	AttemptCount     uint32  `json:"attempt_count"`
	EnqueuedAtMs     float64 `json:"enqueued_at_ms"`
	DeadLetteredAtMs float64 `json:"dead_lettered_at_ms"`
	FailureSummary   *string `json:"failure_summary"`
}

// BatchEnqueueResult Ordered result for one item in a non-atomic batch enqueue.
type BatchEnqueueResult struct {
	JobID     *string `json:"job_id"`
	ErrorCode *string `json:"error_code"`
	Retryable bool    `json:"retryable"`
	Message   *string `json:"message"`
}

// QueueStats Counter-based queue activity and indexed age estimate.
type QueueStats struct {
	EnqueuedTotal        uint64   `json:"enqueued_total"`
	SettledTotal         uint64   `json:"settled_total"`
	DeadTotal            uint64   `json:"dead_total"`
	CancelledTotal       uint64   `json:"cancelled_total"`
	EnqueueRatePerMinute float64  `json:"enqueue_rate_per_minute"`
	SettleRatePerMinute  float64  `json:"settle_rate_per_minute"`
	OldestVisibleAgeMs   *float64 `json:"oldest_visible_age_ms"`
	Paused               bool     `json:"paused"`
}

// DeadLetterPage A bounded page of dead letters.
type DeadLetterPage struct {
	Items  []DeadLetterInfo `json:"items"`
	Cursor *string          `json:"cursor"`
}

// RedriveBatchResult Result of one bounded batch redrive.
type RedriveBatchResult struct {
	Redriven uint32  `json:"redriven"`
	Cursor   *string `json:"cursor"`
}

// OutboxRelayReport Result and backlog snapshot from one outbox relay pass.
type OutboxRelayReport struct {
	Claimed            uint32   `json:"claimed"`
	Dispatched         uint32   `json:"dispatched"`
	Failed             uint32   `json:"failed"`
	Pending            uint64   `json:"pending"`
	OldestPendingAgeMs *float64 `json:"oldest_pending_age_ms"`
}

// ScanPage A page of keys and an opaque continuation cursor.
type ScanPage struct {
	Keys   []string `json:"keys"`
	Cursor *string  `json:"cursor"`
}

// BlobInfo Complete object metadata returned by head.
type BlobInfo struct {
	Key                  string            `json:"key"`
	Size                 uint64            `json:"size"`
	ContentType          string            `json:"content_type"`
	ETag                 string            `json:"etag"`
	LastModifiedMs       float64           `json:"last_modified_ms"`
	Metadata             map[string]string `json:"metadata"`
	CacheControl         *string           `json:"cache_control"`
	ContentDisposition   *string           `json:"content_disposition"`
	ChecksumSha256       *string           `json:"checksum_sha256"`
	ServerSideEncryption *string           `json:"server_side_encryption"`
}

// BlobSummary Lightweight object metadata returned by list; content type and user metadata require head.
type BlobSummary struct {
	Key            string  `json:"key"`
	Size           uint64  `json:"size"`
	ETag           string  `json:"etag"`
	LastModifiedMs float64 `json:"last_modified_ms"`
}

// BlobPage A page of blob summaries and an opaque continuation cursor.
type BlobPage struct {
	Items  []BlobSummary `json:"items"`
	Cursor *string       `json:"cursor"`
}

// ConditionalBlobGet Atomic conditional-read result that distinguishes missing and not-modified.
type ConditionalBlobGet struct {
	State string  `json:"state"`
	Body  *[]byte `json:"body"`
	ETag  *string `json:"etag"`
}

// MultipartUpload Opaque provider-native server-mediated multipart upload handle.
type MultipartUpload struct {
	Key          string  `json:"key"`
	UploadID     string  `json:"upload_id"`
	CreateOnly   bool    `json:"create_only"`
	MatchVersion *string `json:"match_version"`
}

// MultipartPart One uploaded multipart part receipt.
type MultipartPart struct {
	PartNumber uint32 `json:"part_number"`
	ETag       string `json:"etag"`
	Size       uint64 `json:"size"`
}

// ProxyPresign Forge proxy-signed request whose server-side proxy can enforce an upload-size ceiling.
type ProxyPresign struct {
	URL             string            `json:"url"`
	Method          string            `json:"method"`
	Key             string            `json:"key"`
	ExpiresEpoch    int64             `json:"expires_epoch"`
	MaxBytes        uint64            `json:"max_bytes"`
	Signature       string            `json:"signature"`
	RequiredHeaders map[string]string `json:"required_headers"`
}

// NativePresign Provider-native presigned request. Native PUT does not portably enforce a maximum body size.
type NativePresign struct {
	URL             string            `json:"url"`
	Method          string            `json:"method"`
	ExpiresEpoch    int64             `json:"expires_epoch"`
	RequiredHeaders map[string]string `json:"required_headers"`
	Constraints     map[string]string `json:"constraints"`
}

// ScheduleInfo A registered schedule.
type ScheduleInfo struct {
	Name          string   `json:"name"`
	Kind          string   `json:"kind"`
	CronExpr      *string  `json:"cron_expr"`
	Queue         string   `json:"queue"`
	NextRunMs     float64  `json:"next_run_ms"`
	LastRunMs     *float64 `json:"last_run_ms"`
	Paused        bool     `json:"paused"`
	MisfirePolicy string   `json:"misfire_policy"`
	MaxCatchUp    uint32   `json:"max_catch_up"`
}

// SchedulePage A page of schedules and an opaque continuation cursor.
type SchedulePage struct {
	Items  []ScheduleInfo `json:"items"`
	Cursor *string        `json:"cursor"`
}

// SchedulerDiagnostics Bounded operational state for one scheduler namespace.
type SchedulerDiagnostics struct {
	LagMs                *float64 `json:"lag_ms"`
	LastSuccessfulTickMs *float64 `json:"last_successful_tick_ms"`
	DueCount             uint64   `json:"due_count"`
	EnqueueFailures      uint64   `json:"enqueue_failures"`
}

// Session Validated session metadata.
type Session struct {
	UserID      string  `json:"user_id"`
	CreatedAtMs float64 `json:"created_at_ms"`
	ExpiresAtMs float64 `json:"expires_at_ms"`
}

// ApiKeyInfo Non-secret API-key metadata.
type ApiKeyInfo struct {
	ID          string            `json:"id"`
	OwnerID     string            `json:"owner_id"`
	Label       string            `json:"label"`
	ExpiresAtMs *float64          `json:"expires_at_ms"`
	Scopes      []string          `json:"scopes"`
	Metadata    map[string]string `json:"metadata"`
}

// TokenConsumption The user and bounded opaque payload returned by atomic one-time-token consumption.
type TokenConsumption struct {
	UserID  string `json:"user_id"`
	Payload []byte `json:"payload"`
}

// FlagEvaluation Typed OpenFeature-style flag result with stable evaluation details.
type FlagEvaluation struct {
	ValueJSON string  `json:"value_json"`
	ValueType string  `json:"value_type"`
	Variant   *string `json:"variant"`
	Reason    string  `json:"reason"`
	ErrorCode *string `json:"error_code"`
}

// ConfigEntry One config value returned in the same order as its requested key.
type ConfigEntry struct {
	Key   string  `json:"key"`
	Value *string `json:"value"`
}

// FlagEvaluationRequest One typed bulk flag evaluation with a caller-owned correlation id.
type FlagEvaluationRequest struct {
	ID           string  `json:"id"`
	Key          string  `json:"key"`
	DefaultJSON  string  `json:"default_json"`
	TargetingKey *string `json:"targeting_key"`
	ContextJSON  *string `json:"context_json"`
}

// FlagEvaluationEntry One typed bulk flag result in request order.
type FlagEvaluationEntry struct {
	ID         string         `json:"id"`
	Key        string         `json:"key"`
	Evaluation FlagEvaluation `json:"evaluation"`
}

// ConfigSnapshot Read-only caller-scoped config view with an explicit expiry and secret-handling declaration.
type ConfigSnapshot struct {
	SchemaVersion  uint32                `json:"schema_version"`
	CreatedAtMs    float64               `json:"created_at_ms"`
	ExpiresAtMs    float64               `json:"expires_at_ms"`
	SecretHandling string                `json:"secret_handling"`
	Config         []ConfigEntry         `json:"config"`
	Flags          []FlagEvaluationEntry `json:"flags"`
}

// BackendInfo Resolved backend capability information.
type BackendInfo struct {
	Primitive string `json:"primitive"`
	Provider  string `json:"provider"`
	Durable   bool   `json:"durable"`
	Caveats   string `json:"caveats"`
}

// BackendHealth One redacted live backend probe result.
type BackendHealth struct {
	Primitive     string   `json:"primitive"`
	Provider      string   `json:"provider"`
	Status        string   `json:"status"`
	LatencyMs     float64  `json:"latency_ms"`
	ErrorCategory *string  `json:"error_category"`
	LastSuccessMs *float64 `json:"last_success_ms"`
	Message       string   `json:"message"`
}

// HealthReport Separate process liveness and dependency readiness.
type HealthReport struct {
	Live        bool            `json:"live"`
	Ready       bool            `json:"ready"`
	CheckedAtMs float64         `json:"checked_at_ms"`
	DurationMs  float64         `json:"duration_ms"`
	Backends    []BackendHealth `json:"backends"`
}

// MetricSample One bounded-cardinality per-instance metric sample.
type MetricSample struct {
	Name   string            `json:"name"`
	Kind   string            `json:"kind"`
	Labels map[string]string `json:"labels"`
	Value  float64           `json:"value"`
	Count  *uint64           `json:"count"`
	Sum    *float64          `json:"sum"`
}

// DiagnosticCheck One secret-safe deployment or operator diagnostic.
type DiagnosticCheck struct {
	Name    string `json:"name"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

// DiagnosticsReport Bounded configuration, schema, permission, reachability, skew, and safety checks.
type DiagnosticsReport struct {
	Ready       bool              `json:"ready"`
	CheckedAtMs float64           `json:"checked_at_ms"`
	Checks      []DiagnosticCheck `json:"checks"`
}

// MigrationReport Structured migration outcome for one distinct PostgreSQL target.
type MigrationReport struct {
	Target         string   `json:"target"`
	State          string   `json:"state"`
	CurrentVersion *string  `json:"current_version"`
	TargetVersion  string   `json:"target_version"`
	Applied        []string `json:"applied"`
	Pending        []string `json:"pending"`
	LockHolder     *string  `json:"lock_holder"`
	Message        string   `json:"message"`
}
