#!/usr/bin/env python3
"""Generate the Go module's embedded migrations from the canonical Rust sources."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "bindings" / "go" / "migrations_gen.go"


def render() -> str:
    bootstrap = (ROOT / "src" / "migrations" / "bootstrap.sql").read_text(encoding="utf-8")
    migrations = sorted((ROOT / "src" / "migrations").glob("v*.sql"))
    lines = [
        "// Code generated by tools/go-migrations/generate.py. DO NOT EDIT.",
        "",
        "package forge",
        "",
        f"const bootstrapSQL = {json.dumps(bootstrap)}",
        "",
        "var canonicalMigrations = []migrationSource{",
    ]
    for path in migrations:
        lines.append(f"\t{{version: {json.dumps(path.stem)}, sql: {json.dumps(path.read_text(encoding='utf-8'))}}},")
    lines.extend(["}", ""])
    return "\n".join(lines)


def formatted(content: str) -> str:
    result = subprocess.run(["gofmt"], input=content, text=True, capture_output=True, check=True)
    return result.stdout


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = formatted(render())
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"stale generated file: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("Go migrations match canonical SQL")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
