// @generated by tools/codegen — DO NOT EDIT.
// Source of truth: tools/codegen/src/schema.rs
// Regenerate: cargo run --manifest-path tools/codegen/Cargo.toml
// Included via `include!` into lib.rs, so it relies on lib.rs's imports (napi, HashMap).

/// A leased job. Settle it with ack/nack/heartbeat using the opaque, delivery-unique `receipt`
/// (not `id`, which is stable across redeliveries and is the natural idempotency key).
#[napi(object)]
pub struct JsJob {
    pub id: String,
    /// Delivery-unique handle for ack/nack/heartbeat (SQS ReceiptHandle).
    pub receipt: String,
    pub payload: String,
    pub attempt: u32,
    pub max_attempts: u32,
    pub leased_until_ms: f64,
    pub queue: String,
}

/// A rate-limit decision (maps onto the IETF RateLimit header fields).
#[napi(object)]
pub struct JsDecision {
    pub allowed: bool,
    pub limit: u32,
    pub remaining: u32,
    /// Seconds until the limit fully resets (the IETF `RateLimit-Reset` value).
    pub reset_after_seconds: f64,
    pub retry_after_seconds: Option<f64>,
}

/// A freshly minted API key. `secret` is shown exactly once.
#[napi(object)]
pub struct JsApiKey {
    pub id: String,
    pub secret: String,
    pub label: String,
    pub created_at_ms: f64,
}

/// Approximate queue depth (SQS ApproximateNumberOfMessages{,NotVisible,Delayed}).
#[napi(object)]
pub struct JsQueueDepth {
    pub visible: u32,
    pub in_flight: u32,
    pub delayed: u32,
}

/// One page of a kv scan: the keys plus an opaque next-page `cursor` (absent when iteration is
/// complete).
#[napi(object)]
pub struct JsScanPage {
    pub keys: Vec<String>,
    pub cursor: Option<String>,
}

/// Object metadata (S3 HeadObject). `last_modified_ms` is epoch milliseconds.
#[napi(object)]
pub struct JsBlobInfo {
    pub key: String,
    pub size: f64,
    pub content_type: String,
    pub etag: String,
    pub last_modified_ms: f64,
    pub metadata: HashMap<String, String>,
}

/// One page of a blob list: the objects plus an opaque next-page `cursor` (absent when
/// iteration is complete).
#[napi(object)]
pub struct JsBlobPage {
    pub items: Vec<JsBlobInfo>,
    pub cursor: Option<String>,
}

/// A registered schedule. `kind` is "cron" or "at"; `cron_expr` is set only for crons. Times
/// are epoch milliseconds.
#[napi(object)]
pub struct JsScheduleInfo {
    pub name: String,
    pub kind: String,
    pub cron_expr: Option<String>,
    pub queue: String,
    pub next_run_ms: f64,
    pub last_run_ms: Option<f64>,
}

/// One page of a schedule list: the schedules plus an opaque next-page `cursor` (absent when
/// iteration is complete).
#[napi(object)]
pub struct JsSchedulePage {
    pub items: Vec<JsScheduleInfo>,
    pub cursor: Option<String>,
}

/// A validated session's metadata. Times are epoch milliseconds.
#[napi(object)]
pub struct JsSession {
    pub user_id: String,
    pub created_at_ms: f64,
    pub expires_at_ms: f64,
}

/// Non-secret API-key metadata.
#[napi(object)]
pub struct JsApiKeyInfo {
    pub id: String,
    pub owner_id: String,
    pub label: String,
}

/// One line of a backend report: which provider powers a primitive.
#[napi(object)]
pub struct JsBackendInfo {
    pub primitive: String,
    pub provider: String,
    pub durable: bool,
    pub caveats: String,
}
