from __future__ import annotations

import asyncio
from typing import Any, AsyncIterator, Awaitable, Callable, Generic, Optional, TypeVar

from ._generated import (
    ApiKey,
    ApiKeyInfo,
    BackendInfo,
    BlobInfo,
    BlobListPage,
    Decision,
    Job,
    QueueDepth,
    ScanPage,
    ScheduleInfo,
    SchedulePage,
    SessionInfo,
)

T = TypeVar("T")
Loads = Callable[[str], T]
Dumps = Callable[[T], str]

class ForgeError(Exception): ...
class NotFound(ForgeError): ...
class Invalid(ForgeError): ...
class Limit(ForgeError): ...
class Precondition(ForgeError): ...
class Unavailable(ForgeError): ...
class Config(ForgeError): ...
class Backend(ForgeError): ...

class Subscription(AsyncIterator[bytes]):
    def __aiter__(self) -> Subscription: ...
    async def __anext__(self) -> bytes: ...
    def aclose(self) -> Awaitable[None]: ...

class QueueJob(Generic[T]):
    id: str
    receipt: str
    attempt: int
    max_attempts: int
    leased_until_ms: float
    queue: str
    payload: T
    lease_lost: Optional[asyncio.Event]
    def __init__(
        self,
        id: str,
        receipt: str,
        attempt: int,
        max_attempts: int,
        leased_until_ms: float,
        queue: str,
        payload: T,
        lease_lost: Optional[asyncio.Event] = ...,
    ) -> None: ...

class Queue(Generic[T]):
    def __init__(
        self,
        client: ForgeClient,
        name: str,
        *,
        loads: Loads[T] = ...,
        dumps: Dumps[T] = ...,
    ) -> None: ...
    async def enqueue(
        self,
        payload: T,
        *,
        max_attempts: Optional[int] = ...,
        dedup_id: Optional[str] = ...,
        delay_seconds: Optional[float] = ...,
    ) -> str: ...
    async def dequeue(
        self,
        *,
        visibility_seconds: float = ...,
        wait_seconds: float = ...,
    ) -> Optional[QueueJob[T]]: ...
    async def ack(self, receipt: str) -> None: ...
    async def nack(self, receipt: str, retry_seconds: Optional[float] = ...) -> None: ...
    async def heartbeat(self, receipt: str) -> None: ...
    async def depth(self) -> QueueDepth: ...
    async def worker(
        self,
        handler: Callable[[QueueJob[T]], Awaitable[None]],
        *,
        visibility_seconds: float = ...,
        wait_seconds: float = ...,
        stop: Optional[asyncio.Event] = ...,
    ) -> None: ...

class KvKey(Generic[T]):
    def __init__(
        self,
        client: ForgeClient,
        key: str,
        *,
        loads: Loads[T] = ...,
        dumps: Dumps[T] = ...,
    ) -> None: ...
    async def get(self) -> Optional[T]: ...
    async def get_or_default(self, default: T) -> T: ...
    async def set(
        self,
        value: T,
        *,
        ttl_seconds: Optional[float] = ...,
        if_not_exists: Optional[bool] = ...,
        if_exists: Optional[bool] = ...,
    ) -> bool: ...
    async def delete(self) -> bool: ...
    async def exists(self) -> bool: ...
    async def expire(self, ttl_seconds: float) -> bool: ...
    async def compare_and_swap(self, old: Optional[T], new_value: T) -> bool: ...

class ConfigKey(Generic[T]):
    def __init__(
        self,
        client: ForgeClient,
        key: str,
        default: T,
        *,
        loads: Loads[T] = ...,
        dumps: Dumps[T] = ...,
    ) -> None: ...
    async def get(self) -> Optional[T]: ...
    async def get_or_default(self) -> T: ...
    async def set(self, value: T) -> None: ...
    async def delete(self) -> bool: ...

class Topic(Generic[T]):
    def __init__(
        self,
        client: ForgeClient,
        topic: str,
        *,
        loads: Loads[T] = ...,
        dumps: Dumps[T] = ...,
    ) -> None: ...
    async def publish(self, event: T) -> None: ...
    def subscribe(self) -> AsyncIterator[T]: ...

class ForgeClient:
    @staticmethod
    def init() -> Awaitable[ForgeClient]: ...
    @staticmethod
    def init_from(path: str) -> Awaitable[ForgeClient]: ...
    def queue(
        self,
        name: str,
        *,
        loads: Loads[T] = ...,
        dumps: Dumps[T] = ...,
    ) -> Queue[T]: ...
    def kv(
        self,
        key: str,
        *,
        loads: Loads[T] = ...,
        dumps: Dumps[T] = ...,
    ) -> KvKey[T]: ...
    def config(
        self,
        key: str,
        default: T,
        *,
        loads: Loads[T] = ...,
        dumps: Dumps[T] = ...,
    ) -> ConfigKey[T]: ...
    def topic(
        self,
        name: str,
        *,
        loads: Loads[T] = ...,
        dumps: Dumps[T] = ...,
    ) -> Topic[T]: ...
    def worker(
        self,
        name: str,
        handler: Callable[[QueueJob[T]], Awaitable[None]],
        *,
        visibility_seconds: float = ...,
        wait_seconds: float = ...,
        stop: Optional[asyncio.Event] = ...,
        loads: Loads[T] = ...,
    ) -> Awaitable[None]: ...
    def backend_report(self) -> list[BackendInfo]: ...
    def kv_get(self, key: str) -> Awaitable[Optional[str]]: ...
    def kv_get_bytes(self, key: str) -> Awaitable[Optional[bytes]]: ...
    def kv_mget(self, keys: list[str]) -> Awaitable[list[Optional[str]]]: ...
    def kv_set(
        self,
        key: str,
        value: str,
        ttl_seconds: Optional[float] = ...,
        if_not_exists: Optional[bool] = ...,
        if_exists: Optional[bool] = ...,
    ) -> Awaitable[bool]: ...
    def kv_set_bytes(
        self,
        key: str,
        value: bytes,
        ttl_seconds: Optional[float] = ...,
        if_not_exists: Optional[bool] = ...,
    ) -> Awaitable[bool]: ...
    def kv_incr(self, key: str, by: int) -> Awaitable[int]: ...
    def kv_scan(self, prefix: str, limit: int) -> Awaitable[list[str]]: ...
    def kv_delete(self, key: str) -> Awaitable[bool]: ...
    def kv_exists(self, key: str) -> Awaitable[bool]: ...
    def kv_expire(self, key: str, ttl_seconds: float) -> Awaitable[bool]: ...
    def kv_compare_and_swap(
        self, key: str, old: Optional[str], new_value: str
    ) -> Awaitable[bool]: ...
    def kv_scan_page(
        self, prefix: str, cursor: Optional[str] = ..., limit: int = ...
    ) -> Awaitable[ScanPage]: ...
    def queue_enqueue(
        self,
        queue: str,
        payload: str,
        max_attempts: Optional[int] = ...,
        dedup_id: Optional[str] = ...,
        delay_seconds: Optional[float] = ...,
    ) -> Awaitable[str]: ...
    def queue_dequeue(
        self, queue: str, visibility_seconds: float, wait_seconds: float
    ) -> Awaitable[Optional[Job]]: ...
    def queue_ack(self, receipt: str) -> Awaitable[None]: ...
    def queue_nack(
        self, receipt: str, retry_seconds: Optional[float] = ...
    ) -> Awaitable[None]: ...
    def queue_heartbeat(self, receipt: str) -> Awaitable[None]: ...
    def queue_depth(self, queue: str) -> Awaitable[QueueDepth]: ...
    def config_set(self, key: str, value: str) -> Awaitable[None]: ...
    def config_get(self, key: str) -> Awaitable[Optional[str]]: ...
    def config_delete(self, key: str) -> Awaitable[bool]: ...
    def set_flag_percent(self, key: str, percent: int) -> Awaitable[None]: ...
    def set_flag_on(self, key: str) -> Awaitable[None]: ...
    def set_flag_off(self, key: str) -> Awaitable[None]: ...
    def set_flag_allow_list(self, key: str, entries: list[str]) -> Awaitable[None]: ...
    def delete_flag(self, key: str) -> Awaitable[bool]: ...
    def flag(
        self, key: str, default_value: bool, targeting_key: Optional[str] = ...
    ) -> Awaitable[bool]: ...
    def rate_limit_check(
        self,
        bucket: str,
        key: str,
        max: int,
        per_seconds: float,
        fail_open: Optional[bool] = ...,
        algo: Optional[str] = ...,
    ) -> Awaitable[Decision]: ...
    def blob_put(
        self, key: str, data: bytes, content_type: Optional[str] = ...
    ) -> Awaitable[None]: ...
    def blob_put_object(
        self,
        key: str,
        data: bytes,
        content_type: Optional[str] = ...,
        metadata: Optional[dict[str, str]] = ...,
    ) -> Awaitable[None]: ...
    def blob_get(self, key: str) -> Awaitable[Optional[bytes]]: ...
    def blob_head(self, key: str) -> Awaitable[Optional[BlobInfo]]: ...
    def blob_list(
        self, prefix: str, cursor: Optional[str] = ..., limit: int = ...
    ) -> Awaitable[BlobListPage]: ...
    def blob_presign_download(self, key: str, expires_seconds: float) -> Awaitable[str]: ...
    def blob_presign_upload(
        self, key: str, expires_seconds: float, max_bytes: int
    ) -> Awaitable[str]: ...
    def blob_verify_presign(
        self, method: str, key: str, expires_epoch: int, max_bytes: int, sig: str
    ) -> Awaitable[bool]: ...
    def blob_content_type(self, key: str) -> Awaitable[Optional[str]]: ...
    def blob_delete(self, key: str) -> Awaitable[bool]: ...
    def hash_password(self, plain: str) -> Awaitable[str]: ...
    def verify_password(self, plain: str, hash: str) -> Awaitable[bool]: ...
    def needs_rehash(self, hash: str) -> bool: ...
    def create_session(
        self,
        user_id: str,
        idle_seconds: Optional[float] = ...,
        absolute_seconds: Optional[float] = ...,
    ) -> Awaitable[str]: ...
    def validate_session(self, token: str) -> Awaitable[Optional[str]]: ...
    def validate_session_info(self, token: str) -> Awaitable[Optional[SessionInfo]]: ...
    def revoke_session(self, token: str) -> Awaitable[None]: ...
    def revoke_all_sessions(self, user_id: str) -> Awaitable[int]: ...
    def create_api_key(self, owner_id: str, label: str) -> Awaitable[ApiKey]: ...
    def verify_api_key(self, key: str) -> Awaitable[Optional[str]]: ...
    def verify_api_key_info(self, key: str) -> Awaitable[Optional[ApiKeyInfo]]: ...
    def revoke_api_key(self, id: str) -> Awaitable[bool]: ...
    def schedule_at(
        self,
        when_epoch_ms: float,
        queue: str,
        payload: str,
        max_attempts: Optional[int] = ...,
    ) -> Awaitable[str]: ...
    def schedule_cron(
        self,
        name: str,
        expr: str,
        queue: str,
        payload: str,
        max_attempts: Optional[int] = ...,
    ) -> Awaitable[None]: ...
    def schedule_cancel(self, name: str) -> Awaitable[bool]: ...
    def schedule_cancel_at(self, job_id: str) -> Awaitable[bool]: ...
    def schedule_list(
        self, cursor: Optional[str] = ..., limit: Optional[int] = ...
    ) -> Awaitable[SchedulePage]: ...
    def run_scheduler_once(self) -> Awaitable[int]: ...
    def maintain(self) -> Awaitable[None]: ...
    def pubsub_publish(self, topic: str, payload: str) -> Awaitable[None]: ...
    def pubsub_subscribe(self, topic: str) -> Awaitable[Subscription]: ...
    def pubsub_channel(self, topic: str) -> str: ...

def forge_error_code(exc: BaseException) -> str: ...
def forge_error_retryable(exc: BaseException) -> bool: ...
def queue(
    client: ForgeClient,
    name: str,
    *,
    loads: Loads[T] = ...,
    dumps: Dumps[T] = ...,
) -> Queue[T]: ...
def kv(
    client: ForgeClient,
    key: str,
    *,
    loads: Loads[T] = ...,
    dumps: Dumps[T] = ...,
) -> KvKey[T]: ...
def config(
    client: ForgeClient,
    key: str,
    default: T,
    *,
    loads: Loads[T] = ...,
    dumps: Dumps[T] = ...,
) -> ConfigKey[T]: ...
def topic(
    client: ForgeClient,
    name: str,
    *,
    loads: Loads[T] = ...,
    dumps: Dumps[T] = ...,
) -> Topic[T]: ...
async def run_worker(
    client: ForgeClient,
    queue_name: str,
    handler: Callable[[QueueJob[T]], Awaitable[None]],
    *,
    visibility_seconds: float = ...,
    wait_seconds: float = ...,
    stop: Optional[asyncio.Event] = ...,
    loads: Loads[T] = ...,
) -> None: ...
