# @generated by tools/codegen. DO NOT EDIT.
# Source of truth: tools/codegen/src/schema.rs
# Regenerate: cargo run --manifest-path tools/codegen/Cargo.toml
from __future__ import annotations
from typing import Optional

class Job:
    """A leased job. Settle it with ack/nack/heartbeat using the opaque, delivery-unique `receipt` (not `id`, which is stable across redeliveries and is the natural idempotency key)."""
    id: str
    receipt: str
    payload: str
    attempt: int
    max_attempts: int
    leased_until_ms: float
    queue: str

class Decision:
    """A rate-limit decision (maps onto the IETF RateLimit header fields)."""
    allowed: bool
    limit: int
    remaining: int
    reset_after_seconds: float
    retry_after_seconds: Optional[float]

class ApiKey:
    """A freshly minted API key. `secret` is shown exactly once."""
    id: str
    secret: str
    label: str
    created_at_ms: float

class QueueDepth:
    """Approximate queue depth (SQS ApproximateNumberOfMessages{,NotVisible,Delayed})."""
    visible: int
    in_flight: int
    delayed: int

class ScanPage:
    """One page of a kv scan: the keys plus an opaque next-page `cursor` (absent when iteration is complete)."""
    keys: list[str]
    cursor: Optional[str]

class BlobInfo:
    """Object metadata (S3 HeadObject). `last_modified_ms` is epoch milliseconds."""
    key: str
    size: int
    content_type: str
    etag: str
    last_modified_ms: float
    metadata: dict[str, str]

class BlobListPage:
    """One page of a blob list: the objects plus an opaque next-page `cursor` (absent when iteration is complete)."""
    items: list[BlobInfo]
    cursor: Optional[str]

class ScheduleInfo:
    """A registered schedule. `kind` is "cron" or "at"; `cron_expr` is set only for crons. Times are epoch milliseconds."""
    name: str
    kind: str
    cron_expr: Optional[str]
    queue: str
    next_run_ms: float
    last_run_ms: Optional[float]

class SchedulePage:
    """One page of a schedule list: the schedules plus an opaque next-page `cursor` (absent when iteration is complete)."""
    items: list[ScheduleInfo]
    cursor: Optional[str]

class SessionInfo:
    """A validated session's metadata. Times are epoch milliseconds."""
    user_id: str
    created_at_ms: float
    expires_at_ms: float

class ApiKeyInfo:
    """Non-secret API-key metadata."""
    id: str
    owner_id: str
    label: str

class BackendInfo:
    """One line of a backend report: which provider powers a primitive."""
    primitive: str
    provider: str
    durable: bool
    caveats: str
