# @generated by tools/contract/generate.py. DO NOT EDIT.
# Source of truth: contract/forge.json
from __future__ import annotations
from typing import Optional

class Job:
    """A leased queue job."""
    id: str
    receipt: str
    payload: bytes
    attempt: int
    max_attempts: int
    leased_until_ms: float
    queue: str
    traceparent: Optional[str]
    tracestate: Optional[str]
    baggage: Optional[str]

class Decision:
    """A rate-limit decision."""
    allowed: bool
    limit: int
    remaining: int
    reset_after_seconds: float
    retry_after_seconds: Optional[float]

class ApiKey:
    """A freshly minted API key whose secret is shown once."""
    id: str
    secret: str
    label: str
    created_at_ms: float
    expires_at_ms: Optional[float]
    scopes: list[str]
    metadata: dict[str, str]

class QueueDepth:
    """Approximate queue depth."""
    visible: int
    in_flight: int
    delayed: int
    oldest_visible_age_ms: Optional[float]

class DeadLetterInfo:
    """Payload-free operator metadata for one dead letter."""
    job_id: str
    queue: str
    attempt_count: int
    enqueued_at_ms: float
    dead_lettered_at_ms: float
    failure_summary: Optional[str]

class BatchEnqueueResult:
    """Ordered result for one item in a non-atomic batch enqueue."""
    job_id: Optional[str]
    error_code: Optional[str]
    retryable: bool
    message: Optional[str]

class QueueStats:
    """Counter-based queue activity and indexed age estimate."""
    enqueued_total: int
    settled_total: int
    dead_total: int
    cancelled_total: int
    enqueue_rate_per_minute: float
    settle_rate_per_minute: float
    oldest_visible_age_ms: Optional[float]
    paused: bool

class DeadLetterPage:
    """A bounded page of dead letters."""
    items: list[DeadLetterInfo]
    cursor: Optional[str]

class RedriveBatchResult:
    """Result of one bounded batch redrive."""
    redriven: int
    cursor: Optional[str]

class OutboxRelayReport:
    """Result and backlog snapshot from one outbox relay pass."""
    claimed: int
    dispatched: int
    failed: int
    pending: int
    oldest_pending_age_ms: Optional[float]

class ScanPage:
    """A page of keys and an opaque continuation cursor."""
    keys: list[str]
    cursor: Optional[str]

class BlobInfo:
    """Complete object metadata returned by head."""
    key: str
    size: int
    content_type: str
    etag: str
    last_modified_ms: float
    metadata: dict[str, str]
    cache_control: Optional[str]
    content_disposition: Optional[str]
    checksum_sha256: Optional[str]
    server_side_encryption: Optional[str]

class BlobSummary:
    """Lightweight object metadata returned by list; content type and user metadata require head."""
    key: str
    size: int
    etag: str
    last_modified_ms: float

class BlobListPage:
    """A page of blob summaries and an opaque continuation cursor."""
    items: list[BlobSummary]
    cursor: Optional[str]

class ConditionalBlobGet:
    """Atomic conditional-read result that distinguishes missing and not-modified."""
    state: str
    body: Optional[bytes]
    etag: Optional[str]

class MultipartUpload:
    """Opaque provider-native server-mediated multipart upload handle."""
    key: str
    upload_id: str
    create_only: bool
    match_version: Optional[str]

class MultipartPart:
    """One uploaded multipart part receipt."""
    part_number: int
    etag: str
    size: int

class ProxyPresign:
    """Forge proxy-signed request whose server-side proxy can enforce an upload-size ceiling."""
    url: str
    method: str
    key: str
    expires_epoch: int
    max_bytes: int
    signature: str
    required_headers: dict[str, str]

class NativePresign:
    """Provider-native presigned request. Native PUT does not portably enforce a maximum body size."""
    url: str
    method: str
    expires_epoch: int
    required_headers: dict[str, str]
    constraints: dict[str, str]

class ScheduleInfo:
    """A registered schedule."""
    name: str
    kind: str
    cron_expr: Optional[str]
    queue: str
    next_run_ms: float
    last_run_ms: Optional[float]
    paused: bool
    misfire_policy: str
    max_catch_up: int

class SchedulePage:
    """A page of schedules and an opaque continuation cursor."""
    items: list[ScheduleInfo]
    cursor: Optional[str]

class SchedulerDiagnostics:
    """Bounded operational state for one scheduler namespace."""
    lag_ms: Optional[float]
    last_successful_tick_ms: Optional[float]
    due_count: int
    enqueue_failures: int

class SessionInfo:
    """Validated session metadata."""
    user_id: str
    created_at_ms: float
    expires_at_ms: float

class ApiKeyInfo:
    """Non-secret API-key metadata."""
    id: str
    owner_id: str
    label: str
    expires_at_ms: Optional[float]
    scopes: list[str]
    metadata: dict[str, str]

class TokenConsumption:
    """The user and bounded opaque payload returned by atomic one-time-token consumption."""
    user_id: str
    payload: bytes

class FlagEvaluation:
    """Typed OpenFeature-style flag result with stable evaluation details."""
    value_json: str
    value_type: str
    variant: Optional[str]
    reason: str
    error_code: Optional[str]

class ConfigEntry:
    """One config value returned in the same order as its requested key."""
    key: str
    value: Optional[str]

class FlagEvaluationRequest:
    """One typed bulk flag evaluation with a caller-owned correlation id."""
    id: str
    key: str
    default_json: str
    targeting_key: Optional[str]
    context_json: Optional[str]

class FlagEvaluationEntry:
    """One typed bulk flag result in request order."""
    id: str
    key: str
    evaluation: FlagEvaluation

class ConfigSnapshot:
    """Read-only caller-scoped config view with an explicit expiry and secret-handling declaration."""
    schema_version: int
    created_at_ms: float
    expires_at_ms: float
    secret_handling: str
    config: list[ConfigEntry]
    flags: list[FlagEvaluationEntry]

class BackendInfo:
    """Resolved backend capability information."""
    primitive: str
    provider: str
    durable: bool
    caveats: str

class BackendHealth:
    """One redacted live backend probe result."""
    primitive: str
    provider: str
    status: str
    latency_ms: float
    error_category: Optional[str]
    last_success_ms: Optional[float]
    message: str

class HealthReport:
    """Separate process liveness and dependency readiness."""
    live: bool
    ready: bool
    checked_at_ms: float
    duration_ms: float
    backends: list[BackendHealth]

class MetricSample:
    """One bounded-cardinality per-instance metric sample."""
    name: str
    kind: str
    labels: dict[str, str]
    value: float
    count: Optional[int]
    sum: Optional[float]

class DiagnosticCheck:
    """One secret-safe deployment or operator diagnostic."""
    name: str
    status: str
    message: str

class DiagnosticsReport:
    """Bounded configuration, schema, permission, reachability, skew, and safety checks."""
    ready: bool
    checked_at_ms: float
    checks: list[DiagnosticCheck]

class MigrationReport:
    """Structured migration outcome for one distinct PostgreSQL target."""
    target: str
    state: str
    current_version: Optional[str]
    target_version: str
    applied: list[str]
    pending: list[str]
    lock_holder: Optional[str]
    message: str
