mod schema;

use schema::SCHEMA;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let check = std::env::args().any(|a| a == "--check");
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");

    let outputs = [
        (
            root.join("bindings/forge-node/src/types.generated.rs"),
            gen_node(),
        ),
        (
            root.join("bindings/forge-py/src/types.generated.rs"),
            gen_py(),
        ),
        (
            root.join("bindings/forge-py/python/forgelib/_generated.pyi"),
            gen_pyi(),
        ),
    ];

    let mut stale = Vec::new();
    for (path, content) in &outputs {
        let current = fs::read_to_string(path).unwrap_or_default();
        if current == *content {
            continue;
        }
        if check {
            stale.push(path.clone());
        } else {
            fs::write(path, content).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
            println!("generated {}", rel(&root, path));
        }
    }

    if check && !stale.is_empty() {
        eprintln!(
            "binding types are STALE. Run `cargo run --manifest-path tools/codegen/Cargo.toml`:"
        );
        for p in &stale {
            eprintln!("  {}", rel(&root, p));
        }
        std::process::exit(1);
    }
    println!(
        "{} DTOs across {} files, up to date",
        SCHEMA.len(),
        outputs.len()
    );
}

fn rel(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .display()
        .to_string()
}

const NODE_HEADER: &str = "\
// @generated by tools/codegen. DO NOT EDIT.
// Source of truth: tools/codegen/src/schema.rs
// Regenerate: cargo run --manifest-path tools/codegen/Cargo.toml
// Included via `include!` into lib.rs, so it relies on lib.rs's imports (napi, HashMap).
";

/// `#[napi(object)]` structs for the Node binding. napi derives index.d.ts from these.
fn gen_node() -> String {
    let mut out = String::from(NODE_HEADER);
    for dto in SCHEMA {
        out.push('\n');
        out.push_str(&doc_lines("", dto.doc));
        out.push_str("#[napi(object)]\n");
        out.push_str(&format!("pub struct {} {{\n", dto.node_name));
        for f in dto.fields {
            out.push_str(&doc_lines("    ", f.doc));
            out.push_str(&format!("    pub {}: {},\n", f.name, f.ty.node()));
        }
        out.push_str("}\n");
    }
    out
}

const PY_HEADER: &str = "\
// @generated by tools/codegen. DO NOT EDIT.
// Source of truth: tools/codegen/src/schema.rs
// Regenerate: cargo run --manifest-path tools/codegen/Cargo.toml
// Included via `include!` into lib.rs, so it relies on lib.rs's imports (pyclass, HashMap).
";

/// `#[pyclass]` structs for the Python binding.
fn gen_py() -> String {
    let mut out = String::from(PY_HEADER);
    for dto in SCHEMA {
        out.push('\n');
        out.push_str(&doc_lines("", dto.doc));
        out.push_str("#[pyclass(get_all)]\n");
        if dto.clone {
            out.push_str("#[derive(Clone)]\n");
        }
        out.push_str(&format!("struct {} {{\n", dto.py_name));
        for f in dto.fields {
            out.push_str(&doc_lines("    ", f.doc));
            out.push_str(&format!("    {}: {},\n", f.name, f.ty.py()));
        }
        out.push_str("}\n");
    }
    out
}

/// Python `.pyi` type stubs for the same DTOs (pyo3 ships none on its own).
fn gen_pyi() -> String {
    let mut out = String::from(
        "# @generated by tools/codegen. DO NOT EDIT.\n\
         # Source of truth: tools/codegen/src/schema.rs\n\
         # Regenerate: cargo run --manifest-path tools/codegen/Cargo.toml\n\
         from __future__ import annotations\n\
         from typing import Optional\n",
    );
    for dto in SCHEMA {
        out.push_str(&format!("\nclass {}:\n", dto.py_name));
        out.push_str(&format!("    \"\"\"{}\"\"\"\n", dto.doc));
        for f in dto.fields {
            out.push_str(&format!("    {}: {}\n", f.name, f.ty.pyi()));
        }
    }
    out
}

/// Render `text` as `///` (Rust) doc lines, word-wrapped, with `indent` before each.
/// Empty `text` yields nothing.
fn doc_lines(indent: &str, text: &str) -> String {
    if text.is_empty() {
        return String::new();
    }
    let mut out = String::new();
    let mut line = String::new();
    for word in text.split_whitespace() {
        if !line.is_empty() && line.len() + 1 + word.len() > 92 {
            out.push_str(&format!("{indent}/// {line}\n"));
            line.clear();
        }
        if !line.is_empty() {
            line.push(' ');
        }
        line.push_str(word);
    }
    if !line.is_empty() {
        out.push_str(&format!("{indent}/// {line}\n"));
    }
    out
}
