// @generated by tools/contract/generate.py. DO NOT EDIT.
// Source of truth: contract/forge.json

/// A leased queue job.
#[pyclass(get_all)]
struct Job {
    id: String,
    receipt: String,
    payload: Py<PyBytes>,
    attempt: u32,
    max_attempts: u32,
    leased_until_ms: f64,
    queue: String,
    /// Validated W3C traceparent stored outside the payload.
    traceparent: Option<String>,
    /// Validated W3C tracestate.
    tracestate: Option<String>,
    /// Allow-listed W3C baggage only.
    baggage: Option<String>,
}

/// A rate-limit decision.
#[pyclass(get_all)]
struct Decision {
    allowed: bool,
    limit: u32,
    remaining: u32,
    reset_after_seconds: f64,
    retry_after_seconds: Option<f64>,
}

/// A freshly minted API key whose secret is shown once.
#[pyclass(get_all)]
struct ApiKey {
    id: String,
    secret: String,
    label: String,
    created_at_ms: f64,
    expires_at_ms: Option<f64>,
    /// Application-owned authorization labels; Forge stores but does not interpret them.
    scopes: Vec<String>,
    /// Bounded application metadata.
    metadata: HashMap<String, String>,
}

/// Approximate queue depth.
#[pyclass(get_all)]
struct QueueDepth {
    visible: u64,
    in_flight: u64,
    delayed: u64,
    /// Age of the oldest visible job, or null when none is visible.
    oldest_visible_age_ms: Option<f64>,
}

/// Payload-free operator metadata for one dead letter.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct DeadLetterInfo {
    job_id: String,
    queue: String,
    attempt_count: u32,
    enqueued_at_ms: f64,
    dead_lettered_at_ms: f64,
    /// Bounded and redacted.
    failure_summary: Option<String>,
}

/// Ordered result for one item in a non-atomic batch enqueue.
#[pyclass(get_all)]
struct BatchEnqueueResult {
    /// Effective deterministic job ID on success.
    job_id: Option<String>,
    /// Stable Forge error code on failure.
    error_code: Option<String>,
    /// Whether retrying the failed item may succeed unchanged.
    retryable: bool,
    /// Safe bounded failure message.
    message: Option<String>,
}

/// Counter-based queue activity and indexed age estimate.
#[pyclass(get_all)]
struct QueueStats {
    /// Monotonic enqueue counter.
    enqueued_total: u64,
    /// Monotonic terminal settlement counter.
    settled_total: u64,
    /// Monotonic dead-letter transition counter.
    dead_total: u64,
    /// Monotonic cancellation counter.
    cancelled_total: u64,
    /// Lifetime-average enqueue estimate.
    enqueue_rate_per_minute: f64,
    /// Lifetime-average settlement estimate.
    settle_rate_per_minute: f64,
    /// Indexed age of the oldest visible job.
    oldest_visible_age_ms: Option<f64>,
    /// Whether new leases are paused.
    paused: bool,
}

/// A bounded page of dead letters.
#[pyclass(get_all)]
struct DeadLetterPage {
    items: Vec<DeadLetterInfo>,
    cursor: Option<String>,
}

/// Result of one bounded batch redrive.
#[pyclass(get_all)]
struct RedriveBatchResult {
    redriven: u32,
    cursor: Option<String>,
}

/// Result and backlog snapshot from one outbox relay pass.
#[pyclass(get_all)]
struct OutboxRelayReport {
    claimed: u32,
    dispatched: u32,
    failed: u32,
    pending: u64,
    oldest_pending_age_ms: Option<f64>,
}

/// A page of keys and an opaque continuation cursor.
#[pyclass(get_all)]
struct ScanPage {
    keys: Vec<String>,
    cursor: Option<String>,
}

/// Complete object metadata returned by head.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct BlobInfo {
    key: String,
    size: u64,
    content_type: String,
    etag: String,
    last_modified_ms: f64,
    metadata: HashMap<String, String>,
    /// HTTP cache policy stored with the object.
    cache_control: Option<String>,
    /// HTTP download disposition stored with the object.
    content_disposition: Option<String>,
    /// Lowercase SHA-256 hex digest, independent of the provider ETag.
    checksum_sha256: Option<String>,
    /// Provider-managed encryption label when reported by S3.
    server_side_encryption: Option<String>,
}

/// Lightweight object metadata returned by list; content type and user metadata require head.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct BlobSummary {
    key: String,
    size: u64,
    /// Opaque provider version token; not necessarily an MD5 digest.
    etag: String,
    last_modified_ms: f64,
}

/// A page of blob summaries and an opaque continuation cursor.
#[pyclass(get_all)]
struct BlobListPage {
    items: Vec<BlobSummary>,
    cursor: Option<String>,
}

/// Atomic conditional-read result that distinguishes missing and not-modified.
#[pyclass(get_all)]
struct ConditionalBlobGet {
    /// found, not_modified, or missing.
    state: String,
    /// Present only for found.
    body: Option<Py<PyBytes>>,
    /// Opaque version returned for found or not_modified.
    etag: Option<String>,
}

/// Opaque provider-native server-mediated multipart upload handle.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct MultipartUpload {
    /// Exact logical destination key.
    key: String,
    /// Opaque provider upload identifier.
    upload_id: String,
    /// Whether completion must create a new key.
    create_only: bool,
    /// Destination ETag required at completion.
    match_version: Option<String>,
}

/// One uploaded multipart part receipt.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct MultipartPart {
    /// Provider part number in 1..=10000.
    part_number: u32,
    /// Opaque part receipt passed back unchanged.
    etag: String,
    /// Uploaded part size in bytes.
    size: u64,
}

/// Forge proxy-signed request whose server-side proxy can enforce an upload-size ceiling.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct ProxyPresign {
    /// Bearer credential; redact its query string from logs and traces.
    url: String,
    /// GET or PUT.
    method: String,
    /// Logical object key.
    key: String,
    /// Unix expiry in seconds.
    expires_epoch: i64,
    /// Upload ceiling enforced by the Forge proxy; zero for GET.
    max_bytes: u64,
    /// Signature value for proxy verification.
    signature: String,
    /// Headers the caller must send.
    required_headers: HashMap<String, String>,
}

/// Provider-native presigned request. Native PUT does not portably enforce a maximum body size.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct NativePresign {
    /// Bearer credential; redact its query string from logs and traces.
    url: String,
    /// GET or PUT.
    method: String,
    /// Unix expiry in seconds.
    expires_epoch: i64,
    /// Signed headers the caller must send exactly.
    required_headers: HashMap<String, String>,
    /// Structured provider/security constraints.
    constraints: HashMap<String, String>,
}

/// A registered schedule.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct ScheduleInfo {
    name: String,
    kind: String,
    cron_expr: Option<String>,
    queue: String,
    next_run_ms: f64,
    last_run_ms: Option<f64>,
    /// Whether this named schedule is paused.
    paused: bool,
    /// skip, run_once, or catch_up.
    misfire_policy: String,
    /// Maximum missed occurrences dispatched by catch_up; zero otherwise.
    max_catch_up: u32,
}

/// A page of schedules and an opaque continuation cursor.
#[pyclass(get_all)]
struct SchedulePage {
    items: Vec<ScheduleInfo>,
    cursor: Option<String>,
}

/// Bounded operational state for one scheduler namespace.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct SchedulerDiagnostics {
    /// Age of the oldest unpaused due occurrence.
    lag_ms: Option<f64>,
    /// UTC Unix timestamp of the latest successful pass.
    last_successful_tick_ms: Option<f64>,
    /// Unpaused schedules currently due.
    due_count: u64,
    /// Cumulative scheduler enqueue failures.
    enqueue_failures: u64,
}

/// Validated session metadata.
#[pyclass(get_all)]
struct SessionInfo {
    user_id: String,
    created_at_ms: f64,
    expires_at_ms: f64,
}

/// Non-secret API-key metadata.
#[pyclass(get_all)]
struct ApiKeyInfo {
    id: String,
    owner_id: String,
    label: String,
    expires_at_ms: Option<f64>,
    /// Application-owned authorization labels; Forge stores but does not interpret them.
    scopes: Vec<String>,
    /// Bounded application metadata.
    metadata: HashMap<String, String>,
}

/// The user and bounded opaque payload returned by atomic one-time-token consumption.
#[pyclass(get_all)]
struct TokenConsumption {
    /// Application-owned user identifier.
    user_id: String,
    /// Opaque bytes stored with the token.
    payload: Py<PyBytes>,
}

/// Typed OpenFeature-style flag result with stable evaluation details.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct FlagEvaluation {
    /// Canonical JSON value.
    value_json: String,
    /// boolean, string, integer, float, object, array, or null.
    value_type: String,
    /// Stable application-defined variant.
    variant: Option<String>,
    /// Stable evaluation reason.
    reason: String,
    /// Error category when the default was used.
    error_code: Option<String>,
}

/// One config value returned in the same order as its requested key.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct ConfigEntry {
    /// Exact requested key.
    key: String,
    /// Resolved value, or null when unset.
    value: Option<String>,
}

/// One typed bulk flag evaluation with a caller-owned correlation id.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct FlagEvaluationRequest {
    /// Caller-owned id returned unchanged.
    id: String,
    /// Flag key.
    key: String,
    /// Valid JSON default value.
    default_json: String,
    /// Stable evaluation subject.
    targeting_key: Option<String>,
    /// Optional JSON object of invocation-local OpenFeature context fields.
    context_json: Option<String>,
}

/// One typed bulk flag result in request order.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct FlagEvaluationEntry {
    /// Caller-owned request id.
    id: String,
    /// Flag key.
    key: String,
    /// Stable OpenFeature-style details.
    evaluation: FlagEvaluation,
}

/// Read-only caller-scoped config view with an explicit expiry and secret-handling declaration.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct ConfigSnapshot {
    /// Portable snapshot schema version; currently 1.
    schema_version: u32,
    /// Unix epoch milliseconds when captured.
    created_at_ms: f64,
    /// Hard Unix epoch millisecond staleness boundary.
    expires_at_ms: f64,
    /// no_secrets or application_protected.
    secret_handling: String,
    /// Only the exact requested config keys.
    config: Vec<ConfigEntry>,
    /// Pre-evaluated flag requests; no offline re-evaluation.
    flags: Vec<FlagEvaluationEntry>,
}

/// Resolved backend capability information.
#[pyclass(get_all)]
struct BackendInfo {
    primitive: String,
    provider: String,
    durable: bool,
    caveats: String,
}

/// One redacted live backend probe result.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct BackendHealth {
    primitive: String,
    provider: String,
    /// healthy or unhealthy
    status: String,
    latency_ms: f64,
    /// Stable category, never a raw provider error.
    error_category: Option<String>,
    last_success_ms: Option<f64>,
    /// Bounded redacted diagnostic.
    message: String,
}

/// Separate process liveness and dependency readiness.
#[pyclass(get_all)]
struct HealthReport {
    live: bool,
    ready: bool,
    checked_at_ms: f64,
    duration_ms: f64,
    backends: Vec<BackendHealth>,
}

/// One bounded-cardinality per-instance metric sample.
#[pyclass(get_all)]
struct MetricSample {
    name: String,
    /// counter, gauge, or histogram
    kind: String,
    /// Fixed low-cardinality dimensions only.
    labels: HashMap<String, String>,
    /// Counter or gauge value.
    value: f64,
    /// Histogram observation count.
    count: Option<u64>,
    /// Histogram observation sum.
    sum: Option<f64>,
}

/// One secret-safe deployment or operator diagnostic.
#[pyclass(get_all, skip_from_py_object)]
#[derive(Clone)]
struct DiagnosticCheck {
    /// Stable check identifier.
    name: String,
    /// pass, warn, or fail.
    status: String,
    /// Bounded redacted explanation.
    message: String,
}

/// Bounded configuration, schema, permission, reachability, skew, and safety checks.
#[pyclass(get_all)]
struct DiagnosticsReport {
    /// False when any required check fails.
    ready: bool,
    /// Unix epoch milliseconds.
    checked_at_ms: f64,
    /// Stable ordered checks.
    checks: Vec<DiagnosticCheck>,
}

/// Structured migration outcome for one distinct PostgreSQL target.
#[pyclass(get_all)]
struct MigrationReport {
    /// Safe logical target name, never a connection string.
    target: String,
    /// pending, applied, locked, incompatible, or failed
    state: String,
    /// Highest recorded schema version.
    current_version: Option<String>,
    /// Newest migration embedded in this library.
    target_version: String,
    /// Recorded migration versions.
    applied: Vec<String>,
    /// Known migrations not yet applied.
    pending: Vec<String>,
    /// Safe PostgreSQL session identity when another migrator owns the lock.
    lock_holder: Option<String>,
    /// Safe actionable summary.
    message: String,
}
