#!/usr/bin/env python3
"""Generate Go test fixtures from the canonical conformance scenarios."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "bindings" / "go" / "conformance_gen_test.go"
CONTRACT_VECTORS = {
    "canonicalInteropVectors": ROOT / "contract" / "interop-vectors.json",
    "canonicalScopeVectors": ROOT / "contract" / "scope-vectors.json",
}


def render() -> str:
    scenarios = sorted((ROOT / "src" / "conformance" / "scenarios").glob("*.json"))
    lines = [
        "// Code generated by tools/go-conformance/generate.py. DO NOT EDIT.",
        "",
        "package forge",
        "",
        "var canonicalConformanceFixtures = map[string][]byte{",
    ]
    for path in scenarios:
        lines.append(
            f"\t{json.dumps(path.name)}: []byte({json.dumps(path.read_text(encoding='utf-8'))}),"
        )
    lines.extend(["}", ""])
    for name, path in CONTRACT_VECTORS.items():
        lines.append(
            f"var {name} = []byte({json.dumps(path.read_text(encoding='utf-8'))})"
        )
        lines.append("")
    return "\n".join(lines)


def formatted(content: str) -> str:
    result = subprocess.run(
        ["gofmt"], input=content, text=True, capture_output=True, check=True
    )
    return result.stdout


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = formatted(render())
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"stale generated file: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("Go conformance fixtures match canonical scenarios")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
