// @generated by FORGE - DO NOT EDIT
// Run `forge generate` after adding or modifying models

// Model types will be generated here based on your Rust schema
// Example: export interface User { id: string; name: string; }

// Common types (re-exported from @forge-rs/svelte for convenience)
export type { ForgeError, QueryResult, SubscriptionResult } from "@forge-rs/svelte";

export type Cursor = string;

export interface PageInfo {
  has_next_page: boolean;
  end_cursor?: Cursor;
  total_count?: number;
}

export interface Page<T> {
  items: T[];
  page_info: PageInfo;
}
