// @generated by FORGE - DO NOT EDIT

import { listTodosStore$, meStore$, createTodo, deleteTodo, login, refreshToken, register, updateTodo } from "./api";
import { toReactive, type ReactiveQuery, toReactiveMutation, type ReactiveMutation } from "./runes.svelte";
import type { AuthResponse, CreateTodoInput, LoginInput, RefreshInput, RegisterInput, Todo, TokenPair, UpdateTodoInput, UserPublic } from "./types";
export const listTodos$ = (): ReactiveQuery<Todo[]> =>
  toReactive(listTodosStore$());
export const me$ = (): ReactiveQuery<UserPublic> =>
  toReactive(meStore$());
export const createTodo$ = (): ReactiveMutation<CreateTodoInput, Todo> =>
  toReactiveMutation(createTodo);
export const deleteTodo$ = (): ReactiveMutation<{ id: string }, boolean> =>
  toReactiveMutation(deleteTodo);
export const login$ = (): ReactiveMutation<LoginInput, AuthResponse> =>
  toReactiveMutation(login);
export const refreshToken$ = (): ReactiveMutation<RefreshInput, TokenPair> =>
  toReactiveMutation(refreshToken);
export const register$ = (): ReactiveMutation<RegisterInput, AuthResponse> =>
  toReactiveMutation(register);
export const updateTodo$ = (): ReactiveMutation<UpdateTodoInput, Todo> =>
  toReactiveMutation(updateTodo);
