// @generated by FORGE - DO NOT EDIT

import { listTodosStore$, createTodo, deleteTodo, updateTodo } from "./api";
import { toReactive, type ReactiveQuery, toReactiveMutation, type ReactiveMutation } from "./runes.svelte";
import type { CreateTodoInput, Todo, UpdateTodoInput } from "./types";
export const listTodos$ = (): ReactiveQuery<Todo[]> =>
  toReactive(listTodosStore$());
export const createTodo$ = (): ReactiveMutation<CreateTodoInput, Todo> =>
  toReactiveMutation(createTodo);
export const deleteTodo$ = (): ReactiveMutation<{ id: string }, boolean> =>
  toReactiveMutation(deleteTodo);
export const updateTodo$ = (): ReactiveMutation<UpdateTodoInput, Todo> =>
  toReactiveMutation(updateTodo);
