// @generated by FORGE - DO NOT EDIT

export interface CreateTodoInput {
  title: string;
}

export interface Todo {
  id: string;
  title: string;
  completed: boolean;
  created_at: string;
}

export interface UpdateTodoInput {
  id: string;
  title?: string;
  completed?: boolean;
}

export type Cursor = string;

export interface PageInfo {
  has_next_page: boolean;
  end_cursor?: Cursor;
  total_count?: number;
}

export interface Page<T> {
  items: T[];
  page_info: PageInfo;
}

export type { ForgeError, QueryResult, SubscriptionResult } from "@forge-rs/svelte";
