// @generated by FORGE - DO NOT EDIT

export interface AuthResponse {
  access_token: string;
  refresh_token: string;
  user: UserPublic;
}

export interface CreateTodoInput {
  title: string;
}

export interface LoginInput {
  email: string;
  password: string;
}

export interface RefreshInput {
  refresh_token: string;
}

export interface RegisterInput {
  email: string;
  name: string;
  password: string;
}

export interface Todo {
  id: string;
  user_id: string;
  title: string;
  completed: boolean;
  created_at: string;
}

export interface UpdateTodoInput {
  id: string;
  title?: string;
  completed?: boolean;
}

export interface User {
  id: string;
  email: string;
  name: string;
  created_at: string;
  updated_at: string;
}

export interface UserPublic {
  id: string;
  email: string;
  name: string;
}

export type Cursor = string;

export interface PageInfo {
  has_next_page: boolean;
  end_cursor?: Cursor;
  total_count?: number;
}

export interface Page<T> {
  items: T[];
  page_info: PageInfo;
}

export interface TokenPair {
  access_token: string;
  refresh_token: string;
}

export type { ForgeError, QueryResult, SubscriptionResult } from "@forge-rs/svelte";
