// @generated by tools/codegen — DO NOT EDIT.
// Source of truth: tools/codegen/src/schema.rs
// Regenerate: cargo run --manifest-path tools/codegen/Cargo.toml
// Included via `include!` into lib.rs, so it relies on lib.rs's imports (pyclass, HashMap).

/// A leased job. Settle it with ack/nack/heartbeat using the opaque, delivery-unique `receipt`
/// (not `id`, which is stable across redeliveries and is the natural idempotency key).
#[pyclass(get_all)]
struct Job {
    id: String,
    /// Delivery-unique handle for ack/nack/heartbeat (SQS ReceiptHandle).
    receipt: String,
    payload: String,
    attempt: u32,
    max_attempts: u32,
    leased_until_ms: f64,
    queue: String,
}

/// A rate-limit decision (maps onto the IETF RateLimit header fields).
#[pyclass(get_all)]
struct Decision {
    allowed: bool,
    limit: u32,
    remaining: u32,
    /// Seconds until the limit fully resets (the IETF `RateLimit-Reset` value).
    reset_after_seconds: f64,
    retry_after_seconds: Option<f64>,
}

/// A freshly minted API key. `secret` is shown exactly once.
#[pyclass(get_all)]
struct ApiKey {
    id: String,
    secret: String,
    label: String,
    created_at_ms: f64,
}

/// Approximate queue depth (SQS ApproximateNumberOfMessages{,NotVisible,Delayed}).
#[pyclass(get_all)]
struct QueueDepth {
    visible: u64,
    in_flight: u64,
    delayed: u64,
}

/// One page of a kv scan: the keys plus an opaque next-page `cursor` (absent when iteration is
/// complete).
#[pyclass(get_all)]
struct ScanPage {
    keys: Vec<String>,
    cursor: Option<String>,
}

/// Object metadata (S3 HeadObject). `last_modified_ms` is epoch milliseconds.
#[pyclass(get_all)]
#[derive(Clone)]
struct BlobInfo {
    key: String,
    size: u64,
    content_type: String,
    etag: String,
    last_modified_ms: f64,
    metadata: HashMap<String, String>,
}

/// One page of a blob list: the objects plus an opaque next-page `cursor` (absent when
/// iteration is complete).
#[pyclass(get_all)]
struct BlobListPage {
    items: Vec<BlobInfo>,
    cursor: Option<String>,
}

/// A registered schedule. `kind` is "cron" or "at"; `cron_expr` is set only for crons. Times
/// are epoch milliseconds.
#[pyclass(get_all)]
#[derive(Clone)]
struct ScheduleInfo {
    name: String,
    kind: String,
    cron_expr: Option<String>,
    queue: String,
    next_run_ms: f64,
    last_run_ms: Option<f64>,
}

/// One page of a schedule list: the schedules plus an opaque next-page `cursor` (absent when
/// iteration is complete).
#[pyclass(get_all)]
struct SchedulePage {
    items: Vec<ScheduleInfo>,
    cursor: Option<String>,
}

/// A validated session's metadata. Times are epoch milliseconds.
#[pyclass(get_all)]
struct SessionInfo {
    user_id: String,
    created_at_ms: f64,
    expires_at_ms: f64,
}

/// Non-secret API-key metadata.
#[pyclass(get_all)]
struct ApiKeyInfo {
    id: String,
    owner_id: String,
    label: String,
}

/// One line of a backend report: which provider powers a primitive.
#[pyclass(get_all)]
struct BackendInfo {
    primitive: String,
    provider: String,
    durable: bool,
    caveats: String,
}
