// @generated by tools/contract/generate.py. DO NOT EDIT.
// Source of truth: contract/forge.json

/** A leased queue job. */
export interface Job {
  id: string;
  receipt: string;
  payload: Buffer;
  attempt: number;
  maxAttempts: number;
  leasedUntilMs: number;
  queue: string;
  traceparent: string | null;
  tracestate: string | null;
  baggage: string | null;
}

/** A rate-limit decision. */
export interface Decision {
  allowed: boolean;
  limit: number;
  remaining: number;
  resetAfterSeconds: number;
  retryAfterSeconds: number | null;
}

/** A freshly minted API key whose secret is shown once. */
export interface ApiKey {
  id: string;
  secret: string;
  label: string;
  createdAtMs: number;
  expiresAtMs: number | null;
  scopes: Array<string>;
  metadata: Record<string, string>;
}

/** Approximate queue depth. */
export interface QueueDepth {
  visible: number;
  inFlight: number;
  delayed: number;
  oldestVisibleAgeMs: number | null;
}

/** Payload-free operator metadata for one dead letter. */
export interface DeadLetterInfo {
  jobId: string;
  queue: string;
  attemptCount: number;
  enqueuedAtMs: number;
  deadLetteredAtMs: number;
  failureSummary: string | null;
}

/** Ordered result for one item in a non-atomic batch enqueue. */
export interface BatchEnqueueResult {
  jobId: string | null;
  errorCode: string | null;
  retryable: boolean;
  message: string | null;
}

/** Counter-based queue activity and indexed age estimate. */
export interface QueueStats {
  enqueuedTotal: number;
  settledTotal: number;
  deadTotal: number;
  cancelledTotal: number;
  enqueueRatePerMinute: number;
  settleRatePerMinute: number;
  oldestVisibleAgeMs: number | null;
  paused: boolean;
}

/** A bounded page of dead letters. */
export interface DeadLetterPage {
  items: Array<DeadLetterInfo>;
  cursor: string | null;
}

/** Result of one bounded batch redrive. */
export interface RedriveBatchResult {
  redriven: number;
  cursor: string | null;
}

/** Result and backlog snapshot from one outbox relay pass. */
export interface OutboxRelayReport {
  claimed: number;
  dispatched: number;
  failed: number;
  pending: number;
  oldestPendingAgeMs: number | null;
}

/** A page of keys and an opaque continuation cursor. */
export interface ScanPage {
  keys: Array<string>;
  cursor: string | null;
}

/** Complete object metadata returned by head. */
export interface BlobInfo {
  key: string;
  size: number;
  contentType: string;
  etag: string;
  lastModifiedMs: number;
  metadata: Record<string, string>;
  cacheControl: string | null;
  contentDisposition: string | null;
  checksumSha256: string | null;
  serverSideEncryption: string | null;
}

/** Lightweight object metadata returned by list; content type and user metadata require head. */
export interface BlobSummary {
  key: string;
  size: number;
  etag: string;
  lastModifiedMs: number;
}

/** A page of blob summaries and an opaque continuation cursor. */
export interface BlobPage {
  items: Array<BlobSummary>;
  cursor: string | null;
}

/** Atomic conditional-read result that distinguishes missing and not-modified. */
export interface ConditionalBlobGet {
  state: string;
  body: Buffer | null;
  etag: string | null;
}

/** Opaque provider-native server-mediated multipart upload handle. */
export interface MultipartUpload {
  key: string;
  uploadId: string;
  createOnly: boolean;
  matchVersion: string | null;
}

/** One uploaded multipart part receipt. */
export interface MultipartPart {
  partNumber: number;
  etag: string;
  size: number;
}

/** Forge proxy-signed request whose server-side proxy can enforce an upload-size ceiling. */
export interface ProxyPresign {
  url: string;
  method: string;
  key: string;
  expiresEpoch: number;
  maxBytes: number;
  signature: string;
  requiredHeaders: Record<string, string>;
}

/** Provider-native presigned request. Native PUT does not portably enforce a maximum body size. */
export interface NativePresign {
  url: string;
  method: string;
  expiresEpoch: number;
  requiredHeaders: Record<string, string>;
  constraints: Record<string, string>;
}

/** A registered schedule. */
export interface ScheduleInfo {
  name: string;
  kind: string;
  cronExpr: string | null;
  queue: string;
  nextRunMs: number;
  lastRunMs: number | null;
  paused: boolean;
  misfirePolicy: string;
  maxCatchUp: number;
}

/** A page of schedules and an opaque continuation cursor. */
export interface SchedulePage {
  items: Array<ScheduleInfo>;
  cursor: string | null;
}

/** Bounded operational state for one scheduler namespace. */
export interface SchedulerDiagnostics {
  lagMs: number | null;
  lastSuccessfulTickMs: number | null;
  dueCount: number;
  enqueueFailures: number;
}

/** Validated session metadata. */
export interface Session {
  userId: string;
  createdAtMs: number;
  expiresAtMs: number;
}

/** Non-secret API-key metadata. */
export interface ApiKeyInfo {
  id: string;
  ownerId: string;
  label: string;
  expiresAtMs: number | null;
  scopes: Array<string>;
  metadata: Record<string, string>;
}

/** The user and bounded opaque payload returned by atomic one-time-token consumption. */
export interface TokenConsumption {
  userId: string;
  payload: Buffer;
}

/** Typed OpenFeature-style flag result with stable evaluation details. */
export interface FlagEvaluation {
  valueJson: string;
  valueType: string;
  variant: string | null;
  reason: string;
  errorCode: string | null;
}

/** One config value returned in the same order as its requested key. */
export interface ConfigEntry {
  key: string;
  value: string | null;
}

/** One typed bulk flag evaluation with a caller-owned correlation id. */
export interface FlagEvaluationRequest {
  id: string;
  key: string;
  defaultJson: string;
  targetingKey: string | null;
  contextJson: string | null;
}

/** One typed bulk flag result in request order. */
export interface FlagEvaluationEntry {
  id: string;
  key: string;
  evaluation: FlagEvaluation;
}

/** Read-only caller-scoped config view with an explicit expiry and secret-handling declaration. */
export interface ConfigSnapshot {
  schemaVersion: number;
  createdAtMs: number;
  expiresAtMs: number;
  secretHandling: string;
  config: Array<ConfigEntry>;
  flags: Array<FlagEvaluationEntry>;
}

/** Resolved backend capability information. */
export interface BackendInfo {
  primitive: string;
  provider: string;
  durable: boolean;
  caveats: string;
}

/** One redacted live backend probe result. */
export interface BackendHealth {
  primitive: string;
  provider: string;
  status: string;
  latencyMs: number;
  errorCategory: string | null;
  lastSuccessMs: number | null;
  message: string;
}

/** Separate process liveness and dependency readiness. */
export interface HealthReport {
  live: boolean;
  ready: boolean;
  checkedAtMs: number;
  durationMs: number;
  backends: Array<BackendHealth>;
}

/** One bounded-cardinality per-instance metric sample. */
export interface MetricSample {
  name: string;
  kind: string;
  labels: Record<string, string>;
  value: number;
  count: number | null;
  sum: number | null;
}

/** One secret-safe deployment or operator diagnostic. */
export interface DiagnosticCheck {
  name: string;
  status: string;
  message: string;
}

/** Bounded configuration, schema, permission, reachability, skew, and safety checks. */
export interface DiagnosticsReport {
  ready: boolean;
  checkedAtMs: number;
  checks: Array<DiagnosticCheck>;
}

/** Structured migration outcome for one distinct PostgreSQL target. */
export interface MigrationReport {
  target: string;
  state: string;
  currentVersion: string | null;
  targetVersion: string;
  applied: Array<string>;
  pending: Array<string>;
  lockHolder: string | null;
  message: string;
}
