/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A Forge client: one Postgres pool, every primitive. Construct with
 * `ForgeClient.init()`, which reads `forge.toml`.
 */
export declare class ForgeClient {
  /**
   * Read `forge.toml` from the current directory and instantiate the runtime from it;
   * mirrors Rust's `Forge::init`. The file is the single source of configuration; its
   * string values may reference the environment as `${VAR}` / `${VAR:-default}`. Migrates
   * the system database at startup.
   */
  static init(): Promise<ForgeClient>
  /**
   * Like `init`, but reads the `forge.toml` at `path` instead of the one in the current
   * directory.
   */
  static initFrom(path: string): Promise<ForgeClient>
  /**
   * The resolved connection string of Forge's system database — the configured
   * `[postgres] url`, or the DSN an embedded server minted at init. Contains
   * credentials; use it to point the app's own tables/pool at the same database
   * (the only way to reach an embedded server from outside Forge).
   */
  postgresUrl(): string
  /** A backend report: which provider powers each primitive (for health pages/logs). */
  backendReport(): Array<JsBackendInfo>
  /**
   * `GET key` → the value as a UTF-8 string, or `null`. The string surface is
   * UTF-8-only; use `kvGetBytes` for values that may hold arbitrary bytes.
   */
  kvGet(key: string): Promise<string | null>
  /** `GET key` → the raw value bytes, or `null`. Lossless, unlike `kvGet`. */
  kvGetBytes(key: string): Promise<Buffer | null>
  /**
   * `MGET keys` → each value as a UTF-8 string (or `null` if missing/expired), in
   * input order. One round-trip; use instead of a per-key `kvGet` loop.
   */
  kvMget(keys: Array<string>): Promise<Array<string | undefined | null>>
  /**
   * `SET key value`. `ttlSeconds > 0` sets a TTL; `ifNotExists` does `SET NX`.
   * Returns whether the write happened.
   */
  kvSet(key: string, value: string, ttlSeconds?: number | undefined | null, ifNotExists?: boolean | undefined | null, ifExists?: boolean | undefined | null): Promise<boolean>
  /**
   * `SET key` with raw value bytes (lossless, unlike `kvSet`). Returns whether
   * the write happened.
   */
  kvSetBytes(key: string, value: Buffer, ttlSeconds?: number | undefined | null, ifNotExists?: boolean | undefined | null): Promise<boolean>
  /**
   * `INCRBY key by` (atomic). Returns the new value. The counter is an i64
   * core-side, but JS numbers are f64, so a value beyond 2^53 loses precision
   * here (the Python binding returns the exact i64). Real counters never reach
   * that range; if yours might, read it back losslessly via `kvGetBytes`.
   */
  kvIncr(key: string, by: number): Promise<number>
  /** `SCAN prefix*` (first page) → up to `limit` matching keys. */
  kvScan(prefix: string, limit: number): Promise<Array<string>>
  /** `DEL key`. Returns whether the key existed. */
  kvDelete(key: string): Promise<boolean>
  /** `EXISTS key`. Returns whether the key is present (and unexpired). */
  kvExists(key: string): Promise<boolean>
  /** Enqueue a job (string payload). Returns the job id. */
  queueEnqueue(queue: string, payload: string, maxAttempts?: number | undefined | null, dedupId?: string | undefined | null, delaySeconds?: number | undefined | null): Promise<string>
  /**
   * Lease one job for `visibilitySeconds`, long-polling up to `waitSeconds`.
   * `null` if none arrived. `ack`/`nack`/`heartbeat` it by the returned `receipt`.
   */
  queueDequeue(queue: string, visibilitySeconds: number, waitSeconds: number): Promise<JsJob | null>
  /** Ack a leased job by its `receipt` (idempotent: a no-op if already settled). */
  queueAck(receipt: string): Promise<void>
  /**
   * Nack a leased job by its `receipt`; optional `retrySeconds` delays the
   * redelivery. Raises `PRECONDITION` if the receipt is unknown (the lease was
   * lost, stop working on this job).
   */
  queueNack(receipt: string, retrySeconds?: number | undefined | null): Promise<void>
  /**
   * Extend the lease on a job leased by this client (SQS ChangeMessageVisibility /
   * beanstalkd touch) by one visibility timeout. Call before `leasedUntilMs` for a
   * handler that may outlive its visibility window, so the job is not redelivered
   * mid-flight. Raises `PRECONDITION` if the receipt is unknown (the lease was
   * lost, stop working on this job).
   */
  queueHeartbeat(receipt: string): Promise<void>
  /**
   * Approximate `{visible, inFlight, delayed}` counts for a queue (SQS
   * `GetQueueAttributes`). Pass `"<queue>.dlq"` to gauge a dead-letter backlog
   * without leasing its jobs (no side effects, unlike dequeue-to-count).
   */
  queueDepth(queue: string): Promise<JsQueueDepth>
  configSet(key: string, value: string): Promise<void>
  /** Resolve a config value (env `FORGE_CFG_<KEY>` > store > `null`). */
  configGet(key: string): Promise<string | null>
  /** Delete a stored config value. Env `FORGE_CFG_<KEY>` still shadows reads. */
  configDelete(key: string): Promise<boolean>
  /** Set a percentage-rollout flag (`0..=100`). */
  setFlagPercent(key: string, percent: number): Promise<void>
  /**
   * Evaluate a boolean flag for `targetingKey`. Never throws; resolves to
   * `defaultValue` on any failure.
   */
  flag(key: string, defaultValue: boolean, targetingKey?: string | undefined | null): Promise<boolean>
  /**
   * Atomic check-and-consume: `max` per `perSeconds`.
   * `failOpen` overrides what happens on a backend error: omit for the instance
   * default, `true` to allow, `false` to deny. `algo` selects the algorithm:
   * `"token_bucket"` (default) or `"sliding_window"`.
   */
  rateLimitCheck(bucket: string, key: string, max: number, perSeconds: number, failOpen?: boolean | undefined | null, algo?: string | undefined | null): Promise<JsDecision>
  blobPut(key: string, data: string, contentType?: string | undefined | null): Promise<void>
  blobPutBytes(key: string, data: Buffer, contentType?: string | undefined | null): Promise<void>
  /** Fetch an object as a UTF-8 string, or `null`. */
  blobGet(key: string): Promise<string | null>
  /** Fetch an object as raw bytes, or `null`. */
  blobGetBytes(key: string): Promise<Buffer | null>
  /** A presigned download URL (needs a `signingSecret` at connect). */
  blobPresignDownload(key: string, expiresSeconds: number): Promise<string>
  /** A presigned upload (PUT) URL, capped at `maxBytes` (needs a `signingSecret`). */
  blobPresignUpload(key: string, expiresSeconds: number, maxBytes: number): Promise<string>
  /**
   * Verify a presigned URL's query params (needs a `signingSecret`). Returns
   * `true` iff the signature is valid and the URL has not expired; `false` for a
   * bad signature or an expired URL. Throws on no signing secret or a bad method.
   */
  blobVerifyPresign(method: string, key: string, expiresEpoch: number, maxBytes: number, sig: string): Promise<boolean>
  /** The stored content type for an object, or `null` if it does not exist. */
  blobContentType(key: string): Promise<string | null>
  /** Delete an object; returns whether it existed. */
  blobDelete(key: string): Promise<boolean>
  /** argon2id hash of `plain` (a PHC string), to store in your users table. */
  hashPassword(plain: string): Promise<string>
  /** Constant-time verify of `plain` against a stored PHC `hash`. */
  verifyPassword(plain: string, hash: string): Promise<boolean>
  /**
   * Whether a stored PHC `hash` should be re-hashed (its argon2id params are below
   * the current Forge baseline). Call after a successful `verifyPassword`; if `true`,
   * re-hash the plaintext and persist it. Transparent upgrade, no forced reset.
   */
  needsRehash(hash: string): boolean
  /**
   * Create a session for `userId`; returns the opaque token (shown once).
   * Optional sliding `idleSeconds` and hard `absoluteSeconds` deadlines.
   */
  createSession(userId: string, idleSeconds?: number | undefined | null, absoluteSeconds?: number | undefined | null): Promise<string>
  /** Validate a session token; returns the `userId`, or `null`. */
  validateSession(token: string): Promise<string | null>
  /** Revoke a single session by token (log out this device). Idempotent. */
  revokeSession(token: string): Promise<void>
  /** Revoke every session for `userId` (log out everywhere). Returns the count. */
  revokeAllSessions(userId: string): Promise<number>
  /** Mint an `fk_` API key for `ownerId`; the `secret` is shown once. */
  createApiKey(ownerId: string, label: string): Promise<JsApiKey>
  /** Verify an API key; returns the `ownerId`, or `null`. */
  verifyApiKey(key: string): Promise<string | null>
  /**
   * Mint a single-use token scoped to `purpose` (e.g. `"password-reset"`), expiring
   * after `ttlSeconds`; returns the opaque token (shown once). Deliver it out of
   * band (email link, SMS); Forge does not send anything.
   */
  createToken(userId: string, purpose: string, ttlSeconds: number): Promise<string>
  /**
   * Atomically consume a token minted for `purpose`; returns its `userId`, or `null`
   * when unknown/expired/already consumed. A live token presented with the wrong
   * `purpose` is left intact.
   */
  consumeToken(token: string, purpose: string): Promise<string | null>
  /** Schedule a one-shot enqueue at `whenEpochMs`; returns the future JobId. */
  scheduleAt(whenEpochMs: number, queue: string, payload: string, maxAttempts?: number | undefined | null): Promise<string>
  /**
   * Upsert a recurring cron schedule by name. `maxAttempts` overrides the delivery
   * attempts of the job each tick enqueues (omit for the queue default of 5).
   */
  scheduleCron(name: string, expr: string, queue: string, payload: string, maxAttempts?: number | undefined | null): Promise<void>
  /**
   * Fire all due schedules once; returns how many jobs were enqueued. Run on an
   * interval (e.g. every 30s) to drive the scheduler from Node.
   */
  runSchedulerOnce(): Promise<number>
  /**
   * Run periodic housekeeping once: sweep expired kv keys, settled/dead queue
   * jobs, stale ratelimit buckets, and expired sessions. Call on an interval
   * alongside `runSchedulerOnce` (mirrors the Rust `Forge::maintain` loop).
   */
  maintain(): Promise<void>
  /** Publish a payload to a realtime topic (fire-and-forget). */
  pubsubPublish(topic: string, payload: string): Promise<void>
  /**
   * Subscribe to a realtime topic, returning a handle whose `next()` yields each
   * payload published after this resolves (or `null` when the stream ends).
   * Subscriptions share one per-process listener connection; drop the handle to
   * unsubscribe (the channel is released once it has no remaining subscribers).
   */
  pubsubSubscribe(topic: string): Promise<JsSubscription>
  /**
   * The Postgres `LISTEN`/`NOTIFY` channel a topic maps to. `LISTEN` on this with
   * a native Postgres client to receive what `pubsub_publish(topic, …)` sends.
   */
  pubsubChannel(topic: string): string
  /** `EXPIRE key ttlSeconds`. Sets/replaces the TTL on a live key; `false` if absent. */
  kvExpire(key: string, ttlSeconds: number): Promise<boolean>
  /**
   * Atomic compare-and-swap (string values). Writes `newValue` iff the current value
   * equals `old` (`old` omitted means "expected absent/expired"). Returns success.
   */
  kvCompareAndSwap(key: string, old: string | undefined | null, newValue: string): Promise<boolean>
  /**
   * `SCAN prefix*` with cursor pagination. Pass `cursor` from the previous page
   * (omit for the first); the returned `cursor` is `null` when iteration is done.
   */
  kvScanPage(prefix: string, cursor: string | undefined | null, limit: number): Promise<JsScanPage>
  /**
   * `HeadObject`: full metadata (size, content type, etag, last-modified, user
   * metadata), or `null` if the object does not exist.
   */
  blobHead(key: string): Promise<JsBlobInfo | null>
  /**
   * `ListObjectsV2`: up to `limit` objects under `prefix`, lexicographic, with cursor
   * pagination. Pass `cursor` from the previous page (omit for the first).
   */
  blobList(prefix: string, cursor: string | undefined | null, limit: number): Promise<JsBlobPage>
  /** Store an object (binary body) with optional content type and user metadata. */
  blobPutObject(key: string, data: Buffer, contentType?: string | undefined | null, metadata?: Record<string, string> | undefined | null): Promise<void>
  /** Cancel a schedule by name. `true` if one was removed, `false` if none existed. */
  scheduleCancel(name: string): Promise<boolean>
  /**
   * Cancel a one-shot scheduled by `scheduleAt`, by the JobId it returned. `true`
   * if it was still pending and removed, `false` if it already fired or never
   * existed. (Send-later recall / disappearing-message cancellation.)
   */
  scheduleCancelAt(jobId: string): Promise<boolean>
  /**
   * List registered schedules (crons and pending one-shots), ordered by name, up
   * to `limit` per page (default 100) plus an opaque next-page `cursor` (`null`
   * when done). Pass the returned `cursor` back to page through a large backlog.
   */
  scheduleList(cursor?: string | undefined | null, limit?: number | undefined | null): Promise<JsSchedulePage>
  /** Set a flag to always-on. */
  setFlagOn(key: string): Promise<void>
  /** Set a flag to always-off. */
  setFlagOff(key: string): Promise<void>
  /** Set a flag to an allow-list of targeting keys. */
  setFlagAllowList(key: string, entries: Array<string>): Promise<void>
  /** Delete a flag rule. Later `flag` calls fall back to their caller default. */
  deleteFlag(key: string): Promise<boolean>
  /**
   * Validate a session token; returns full session metadata (user id + times), or
   * `null`. Use `validateSession` when only the user id is needed.
   */
  validateSessionInfo(token: string): Promise<JsSession | null>
  /**
   * Verify an API key; returns full non-secret metadata (id, owner, label), or
   * `null`. Use `verifyApiKey` when only the owner id is needed.
   */
  verifyApiKeyInfo(key: string): Promise<JsApiKeyInfo | null>
  /** Revoke an API key by its (non-secret) id. `true` if one was removed. */
  revokeApiKey(id: string): Promise<boolean>
}

/**
 * A live pubsub subscription handle. Drive it as a JS async iterator: call `next()`
 * in a loop until it resolves to `null` (the stream ended). Dropping the handle
 * unsubscribes (subscriptions share one per-process listener connection).
 */
export declare class JsSubscription {
  /** The next published payload as raw bytes, or `null` when the stream ends. */
  next(): Promise<Buffer | null>
  /**
   * Unsubscribe now, releasing the broadcast receiver deterministically instead
   * of waiting for GC. Any pending `next()` resolves to `null` immediately;
   * idempotent; subsequent `next()` calls return `null`. A GraphQL server should
   * call this when a client's WebSocket closes.
   */
  close(): Promise<void>
}

/** A freshly minted API key. `secret` is shown exactly once. */
export interface JsApiKey {
  id: string
  secret: string
  label: string
  createdAtMs: number
}

/** Non-secret API-key metadata. */
export interface JsApiKeyInfo {
  id: string
  ownerId: string
  label: string
}

/** One line of a backend report: which provider powers a primitive. */
export interface JsBackendInfo {
  primitive: string
  provider: string
  durable: boolean
  caveats: string
}

/** Object metadata (S3 HeadObject). `last_modified_ms` is epoch milliseconds. */
export interface JsBlobInfo {
  key: string
  size: number
  contentType: string
  etag: string
  lastModifiedMs: number
  metadata: Record<string, string>
}

/**
 * One page of a blob list: the objects plus an opaque next-page `cursor` (absent when
 * iteration is complete).
 */
export interface JsBlobPage {
  items: Array<JsBlobInfo>
  cursor?: string
}

/** A rate-limit decision (maps onto the IETF RateLimit header fields). */
export interface JsDecision {
  allowed: boolean
  limit: number
  remaining: number
  /** Seconds until the limit fully resets (the IETF `RateLimit-Reset` value). */
  resetAfterSeconds: number
  retryAfterSeconds?: number
}

/**
 * A leased job. Settle it with ack/nack/heartbeat using the opaque, delivery-unique `receipt`
 * (not `id`, which is stable across redeliveries and is the natural idempotency key).
 */
export interface JsJob {
  id: string
  /** Delivery-unique handle for ack/nack/heartbeat (SQS ReceiptHandle). */
  receipt: string
  payload: string
  attempt: number
  maxAttempts: number
  leasedUntilMs: number
  queue: string
}

/** Approximate queue depth (SQS ApproximateNumberOfMessages{,NotVisible,Delayed}). */
export interface JsQueueDepth {
  visible: number
  inFlight: number
  delayed: number
}

/**
 * One page of a kv scan: the keys plus an opaque next-page `cursor` (absent when iteration is
 * complete).
 */
export interface JsScanPage {
  keys: Array<string>
  cursor?: string
}

/**
 * A registered schedule. `kind` is "cron" or "at"; `cron_expr` is set only for crons. Times
 * are epoch milliseconds.
 */
export interface JsScheduleInfo {
  name: string
  kind: string
  cronExpr?: string
  queue: string
  nextRunMs: number
  lastRunMs?: number
}

/**
 * One page of a schedule list: the schedules plus an opaque next-page `cursor` (absent when
 * iteration is complete).
 */
export interface JsSchedulePage {
  items: Array<JsScheduleInfo>
  cursor?: string
}

/** A validated session's metadata. Times are epoch milliseconds. */
export interface JsSession {
  userId: string
  createdAtMs: number
  expiresAtMs: number
}
