use crate::Error;

pub fn generate() -> Result<String, Error> {
    Ok(r#"// @generated by FORGE - DO NOT EDIT
export {
  getForgeClient,
  createConnectionStore,
  createQueryStore,
  createSubscriptionStore,
  createJobStore,
  createWorkflowStore,
} from '@forge-rs/svelte';
export type {
  Readable,
  ConnectionStatusStore,
  QueryStore,
  SubscriptionStore,
  JobStore,
  WorkflowStore,
} from '@forge-rs/svelte';
"#
    .to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_stores_content() {
        let content = generate().expect("stores template should generate");
        assert!(content.contains("@forge-rs/svelte"));
        assert!(content.contains("getForgeClient"));
        assert!(content.contains("createQueryStore"));
        assert!(content.contains("createJobStore"));
        assert!(content.contains("createWorkflowStore"));
    }
}
