// @generated by tools/contract/generate.py. DO NOT EDIT.
// Source of truth: contract/forge.json

/// A leased queue job.
#[napi(object)]
pub struct JsJob {
    pub id: String,
    pub receipt: String,
    pub payload: Buffer,
    pub attempt: u32,
    pub max_attempts: u32,
    pub leased_until_ms: f64,
    pub queue: String,
    /// Validated W3C traceparent stored outside the payload.
    pub traceparent: Option<String>,
    /// Validated W3C tracestate.
    pub tracestate: Option<String>,
    /// Allow-listed W3C baggage only.
    pub baggage: Option<String>,
}

/// A rate-limit decision.
#[napi(object)]
pub struct JsDecision {
    pub allowed: bool,
    pub limit: u32,
    pub remaining: u32,
    pub reset_after_seconds: f64,
    pub retry_after_seconds: Option<f64>,
}

/// A freshly minted API key whose secret is shown once.
#[napi(object)]
pub struct JsApiKey {
    pub id: String,
    pub secret: String,
    pub label: String,
    pub created_at_ms: f64,
    pub expires_at_ms: Option<f64>,
    /// Application-owned authorization labels; Forge stores but does not interpret them.
    pub scopes: Vec<String>,
    /// Bounded application metadata.
    pub metadata: HashMap<String, String>,
}

/// Approximate queue depth.
#[napi(object)]
pub struct JsQueueDepth {
    pub visible: u32,
    pub in_flight: u32,
    pub delayed: u32,
    /// Age of the oldest visible job, or null when none is visible.
    pub oldest_visible_age_ms: Option<f64>,
}

/// Payload-free operator metadata for one dead letter.
#[napi(object)]
pub struct JsDeadLetterInfo {
    pub job_id: String,
    pub queue: String,
    pub attempt_count: u32,
    pub enqueued_at_ms: f64,
    pub dead_lettered_at_ms: f64,
    /// Bounded and redacted.
    pub failure_summary: Option<String>,
}

/// Ordered result for one item in a non-atomic batch enqueue.
#[napi(object)]
pub struct JsBatchEnqueueResult {
    /// Effective deterministic job ID on success.
    pub job_id: Option<String>,
    /// Stable Forge error code on failure.
    pub error_code: Option<String>,
    /// Whether retrying the failed item may succeed unchanged.
    pub retryable: bool,
    /// Safe bounded failure message.
    pub message: Option<String>,
}

/// Counter-based queue activity and indexed age estimate.
#[napi(object)]
pub struct JsQueueStats {
    /// Monotonic enqueue counter.
    pub enqueued_total: u32,
    /// Monotonic terminal settlement counter.
    pub settled_total: u32,
    /// Monotonic dead-letter transition counter.
    pub dead_total: u32,
    /// Monotonic cancellation counter.
    pub cancelled_total: u32,
    /// Lifetime-average enqueue estimate.
    pub enqueue_rate_per_minute: f64,
    /// Lifetime-average settlement estimate.
    pub settle_rate_per_minute: f64,
    /// Indexed age of the oldest visible job.
    pub oldest_visible_age_ms: Option<f64>,
    /// Whether new leases are paused.
    pub paused: bool,
}

/// A bounded page of dead letters.
#[napi(object)]
pub struct JsDeadLetterPage {
    pub items: Vec<JsDeadLetterInfo>,
    pub cursor: Option<String>,
}

/// Result of one bounded batch redrive.
#[napi(object)]
pub struct JsRedriveBatchResult {
    pub redriven: u32,
    pub cursor: Option<String>,
}

/// Result and backlog snapshot from one outbox relay pass.
#[napi(object)]
pub struct JsOutboxRelayReport {
    pub claimed: u32,
    pub dispatched: u32,
    pub failed: u32,
    pub pending: u32,
    pub oldest_pending_age_ms: Option<f64>,
}

/// A page of keys and an opaque continuation cursor.
#[napi(object)]
pub struct JsScanPage {
    pub keys: Vec<String>,
    pub cursor: Option<String>,
}

/// Complete object metadata returned by head.
#[napi(object)]
pub struct JsBlobInfo {
    pub key: String,
    pub size: f64,
    pub content_type: String,
    pub etag: String,
    pub last_modified_ms: f64,
    pub metadata: HashMap<String, String>,
    /// HTTP cache policy stored with the object.
    pub cache_control: Option<String>,
    /// HTTP download disposition stored with the object.
    pub content_disposition: Option<String>,
    /// Lowercase SHA-256 hex digest, independent of the provider ETag.
    pub checksum_sha256: Option<String>,
    /// Provider-managed encryption label when reported by S3.
    pub server_side_encryption: Option<String>,
}

/// Lightweight object metadata returned by list; content type and user metadata require head.
#[napi(object)]
pub struct JsBlobSummary {
    pub key: String,
    pub size: f64,
    /// Opaque provider version token; not necessarily an MD5 digest.
    pub etag: String,
    pub last_modified_ms: f64,
}

/// A page of blob summaries and an opaque continuation cursor.
#[napi(object)]
pub struct JsBlobPage {
    pub items: Vec<JsBlobSummary>,
    pub cursor: Option<String>,
}

/// Atomic conditional-read result that distinguishes missing and not-modified.
#[napi(object)]
pub struct JsConditionalBlobGet {
    /// found, not_modified, or missing.
    pub state: String,
    /// Present only for found.
    pub body: Option<Buffer>,
    /// Opaque version returned for found or not_modified.
    pub etag: Option<String>,
}

/// Opaque provider-native server-mediated multipart upload handle.
#[napi(object)]
pub struct JsMultipartUpload {
    /// Exact logical destination key.
    pub key: String,
    /// Opaque provider upload identifier.
    pub upload_id: String,
    /// Whether completion must create a new key.
    pub create_only: bool,
    /// Destination ETag required at completion.
    pub match_version: Option<String>,
}

/// One uploaded multipart part receipt.
#[napi(object)]
pub struct JsMultipartPart {
    /// Provider part number in 1..=10000.
    pub part_number: u32,
    /// Opaque part receipt passed back unchanged.
    pub etag: String,
    /// Uploaded part size in bytes.
    pub size: f64,
}

/// Forge proxy-signed request whose server-side proxy can enforce an upload-size ceiling.
#[napi(object)]
pub struct JsProxyPresign {
    /// Bearer credential; redact its query string from logs and traces.
    pub url: String,
    /// GET or PUT.
    pub method: String,
    /// Logical object key.
    pub key: String,
    /// Unix expiry in seconds.
    pub expires_epoch: f64,
    /// Upload ceiling enforced by the Forge proxy; zero for GET.
    pub max_bytes: f64,
    /// Signature value for proxy verification.
    pub signature: String,
    /// Headers the caller must send.
    pub required_headers: HashMap<String, String>,
}

/// Provider-native presigned request. Native PUT does not portably enforce a maximum body size.
#[napi(object)]
pub struct JsNativePresign {
    /// Bearer credential; redact its query string from logs and traces.
    pub url: String,
    /// GET or PUT.
    pub method: String,
    /// Unix expiry in seconds.
    pub expires_epoch: f64,
    /// Signed headers the caller must send exactly.
    pub required_headers: HashMap<String, String>,
    /// Structured provider/security constraints.
    pub constraints: HashMap<String, String>,
}

/// A registered schedule.
#[napi(object)]
pub struct JsScheduleInfo {
    pub name: String,
    pub kind: String,
    pub cron_expr: Option<String>,
    pub queue: String,
    pub next_run_ms: f64,
    pub last_run_ms: Option<f64>,
    /// Whether this named schedule is paused.
    pub paused: bool,
    /// skip, run_once, or catch_up.
    pub misfire_policy: String,
    /// Maximum missed occurrences dispatched by catch_up; zero otherwise.
    pub max_catch_up: u32,
}

/// A page of schedules and an opaque continuation cursor.
#[napi(object)]
pub struct JsSchedulePage {
    pub items: Vec<JsScheduleInfo>,
    pub cursor: Option<String>,
}

/// Bounded operational state for one scheduler namespace.
#[napi(object)]
pub struct JsSchedulerDiagnostics {
    /// Age of the oldest unpaused due occurrence.
    pub lag_ms: Option<f64>,
    /// UTC Unix timestamp of the latest successful pass.
    pub last_successful_tick_ms: Option<f64>,
    /// Unpaused schedules currently due.
    pub due_count: u32,
    /// Cumulative scheduler enqueue failures.
    pub enqueue_failures: u32,
}

/// Validated session metadata.
#[napi(object)]
pub struct JsSession {
    pub user_id: String,
    pub created_at_ms: f64,
    pub expires_at_ms: f64,
}

/// Non-secret API-key metadata.
#[napi(object)]
pub struct JsApiKeyInfo {
    pub id: String,
    pub owner_id: String,
    pub label: String,
    pub expires_at_ms: Option<f64>,
    /// Application-owned authorization labels; Forge stores but does not interpret them.
    pub scopes: Vec<String>,
    /// Bounded application metadata.
    pub metadata: HashMap<String, String>,
}

/// The user and bounded opaque payload returned by atomic one-time-token consumption.
#[napi(object)]
pub struct JsTokenConsumption {
    /// Application-owned user identifier.
    pub user_id: String,
    /// Opaque bytes stored with the token.
    pub payload: Buffer,
}

/// Typed OpenFeature-style flag result with stable evaluation details.
#[napi(object)]
pub struct JsFlagEvaluation {
    /// Canonical JSON value.
    pub value_json: String,
    /// boolean, string, integer, float, object, array, or null.
    pub value_type: String,
    /// Stable application-defined variant.
    pub variant: Option<String>,
    /// Stable evaluation reason.
    pub reason: String,
    /// Error category when the default was used.
    pub error_code: Option<String>,
}

/// One config value returned in the same order as its requested key.
#[napi(object)]
pub struct JsConfigEntry {
    /// Exact requested key.
    pub key: String,
    /// Resolved value, or null when unset.
    pub value: Option<String>,
}

/// One typed bulk flag evaluation with a caller-owned correlation id.
#[napi(object)]
pub struct JsFlagEvaluationRequest {
    /// Caller-owned id returned unchanged.
    pub id: String,
    /// Flag key.
    pub key: String,
    /// Valid JSON default value.
    pub default_json: String,
    /// Stable evaluation subject.
    pub targeting_key: Option<String>,
    /// Optional JSON object of invocation-local OpenFeature context fields.
    pub context_json: Option<String>,
}

/// One typed bulk flag result in request order.
#[napi(object)]
pub struct JsFlagEvaluationEntry {
    /// Caller-owned request id.
    pub id: String,
    /// Flag key.
    pub key: String,
    /// Stable OpenFeature-style details.
    pub evaluation: JsFlagEvaluation,
}

/// Read-only caller-scoped config view with an explicit expiry and secret-handling declaration.
#[napi(object)]
pub struct JsConfigSnapshot {
    /// Portable snapshot schema version; currently 1.
    pub schema_version: u32,
    /// Unix epoch milliseconds when captured.
    pub created_at_ms: f64,
    /// Hard Unix epoch millisecond staleness boundary.
    pub expires_at_ms: f64,
    /// no_secrets or application_protected.
    pub secret_handling: String,
    /// Only the exact requested config keys.
    pub config: Vec<JsConfigEntry>,
    /// Pre-evaluated flag requests; no offline re-evaluation.
    pub flags: Vec<JsFlagEvaluationEntry>,
}

/// Resolved backend capability information.
#[napi(object)]
pub struct JsBackendInfo {
    pub primitive: String,
    pub provider: String,
    pub durable: bool,
    pub caveats: String,
}

/// One redacted live backend probe result.
#[napi(object)]
pub struct JsBackendHealth {
    pub primitive: String,
    pub provider: String,
    /// healthy or unhealthy
    pub status: String,
    pub latency_ms: f64,
    /// Stable category, never a raw provider error.
    pub error_category: Option<String>,
    pub last_success_ms: Option<f64>,
    /// Bounded redacted diagnostic.
    pub message: String,
}

/// Separate process liveness and dependency readiness.
#[napi(object)]
pub struct JsHealthReport {
    pub live: bool,
    pub ready: bool,
    pub checked_at_ms: f64,
    pub duration_ms: f64,
    pub backends: Vec<JsBackendHealth>,
}

/// One bounded-cardinality per-instance metric sample.
#[napi(object)]
pub struct JsMetricSample {
    pub name: String,
    /// counter, gauge, or histogram
    pub kind: String,
    /// Fixed low-cardinality dimensions only.
    pub labels: HashMap<String, String>,
    /// Counter or gauge value.
    pub value: f64,
    /// Histogram observation count.
    pub count: Option<u32>,
    /// Histogram observation sum.
    pub sum: Option<f64>,
}

/// One secret-safe deployment or operator diagnostic.
#[napi(object)]
pub struct JsDiagnosticCheck {
    /// Stable check identifier.
    pub name: String,
    /// pass, warn, or fail.
    pub status: String,
    /// Bounded redacted explanation.
    pub message: String,
}

/// Bounded configuration, schema, permission, reachability, skew, and safety checks.
#[napi(object)]
pub struct JsDiagnosticsReport {
    /// False when any required check fails.
    pub ready: bool,
    /// Unix epoch milliseconds.
    pub checked_at_ms: f64,
    /// Stable ordered checks.
    pub checks: Vec<JsDiagnosticCheck>,
}

/// Structured migration outcome for one distinct PostgreSQL target.
#[napi(object)]
pub struct JsMigrationReport {
    /// Safe logical target name, never a connection string.
    pub target: String,
    /// pending, applied, locked, incompatible, or failed
    pub state: String,
    /// Highest recorded schema version.
    pub current_version: Option<String>,
    /// Newest migration embedded in this library.
    pub target_version: String,
    /// Recorded migration versions.
    pub applied: Vec<String>,
    /// Known migrations not yet applied.
    pub pending: Vec<String>,
    /// Safe PostgreSQL session identity when another migrator owns the lock.
    pub lock_holder: Option<String>,
    /// Safe actionable summary.
    pub message: String,
}
