/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A leased job handed to JavaScript. `ack`/`nack` it by `id`. */
export interface JsJob {
  id: string
  payload: string
  attempt: number
}
/**
 * A Forge client: one Postgres pool, every primitive. Construct with
 * `ForgeClient.connect(url)`.
 */
export declare class ForgeClient {
  /** Connect, run migrations, and ping — mirrors `Forge::init`. */
  static connect(postgresUrl: string): Promise<ForgeClient>
  /** `GET key` → the value as a UTF-8 string, or `null`. */
  kvGet(key: string): Promise<string | null>
  /**
   * `SET key value`. `ttlSeconds > 0` sets a TTL; `ifNotExists` does `SET NX`.
   * Returns whether the write happened.
   */
  kvSet(key: string, value: string, ttlSeconds?: number | undefined | null, ifNotExists?: boolean | undefined | null): Promise<boolean>
  /** `INCRBY key by` (atomic). Returns the new value. */
  kvIncr(key: string, by: number): Promise<number>
  /** `SCAN prefix*` (first page) → up to `limit` matching keys. */
  kvScan(prefix: string, limit: number): Promise<Array<string>>
  /** Enqueue a job (string payload). Returns the job id. */
  queueEnqueue(queue: string, payload: string, maxAttempts?: number | undefined | null): Promise<string>
  /**
   * Lease one job for `visibilitySeconds`, long-polling up to `waitSeconds`.
   * `null` if none arrived. `ack`/`nack` it by the returned `id`.
   */
  queueDequeue(queue: string, visibilitySeconds: number, waitSeconds: number): Promise<JsJob | null>
  /** Ack a leased job by id (idempotent). */
  queueAck(id: string): Promise<void>
  /** Nack a leased job by id; optional `retrySeconds` delays the redelivery. */
  queueNack(id: string, retrySeconds?: number | undefined | null): Promise<void>
}
